/*
 * This file is generated from insns.dat, regs.dat and token.dat
 * by tokhash.pl; do not edit.
 */

#include "compiler.h"
#include <string.h>
#include "nasm.h"
#include "hashtbl.h"
#include "insns.h"

struct tokendata {
    const char *string;
    int16_t tokentype;
    int16_t aux;
    int32_t num;
};

int nasm_token_hash(const char *token, struct tokenval *tv)
{
#define UNUSED 16383
    static const int16_t hash1[1024] = {
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -1595,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -2381,
        0,
        UNUSED,
        0,
        824,
        0,
        UNUSED,
        0,
        -1866,
        0,
        UNUSED,
        0,
        408,
        UNUSED,
        520,
        421,
        0,
        0,
        -409,
        UNUSED,
        UNUSED,
        0,
        610,
        0,
        0,
        UNUSED,
        -164,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1989,
        UNUSED,
        0,
        1294,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        289,
        UNUSED,
        UNUSED,
        0,
        1078,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        1,
        UNUSED,
        0,
        UNUSED,
        0,
        978,
        0,
        -3007,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -2030,
        -847,
        UNUSED,
        515,
        0,
        0,
        -466,
        734,
        UNUSED,
        0,
        1488,
        -177,
        UNUSED,
        UNUSED,
        0,
        1027,
        -695,
        0,
        3423,
        UNUSED,
        466,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        -572,
        -3078,
        -2642,
        UNUSED,
        0,
        1156,
        UNUSED,
        UNUSED,
        187,
        UNUSED,
        677,
        0,
        -3340,
        UNUSED,
        UNUSED,
        UNUSED,
        370,
        1272,
        502,
        1286,
        UNUSED,
        221,
        UNUSED,
        -675,
        UNUSED,
        1091,
        UNUSED,
        0,
        -369,
        621,
        0,
        -448,
        0,
        -524,
        0,
        1485,
        UNUSED,
        UNUSED,
        0,
        0,
        779,
        UNUSED,
        0,
        UNUSED,
        345,
        0,
        2713,
        UNUSED,
        0,
        UNUSED,
        1087,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        115,
        UNUSED,
        745,
        UNUSED,
        433,
        747,
        UNUSED,
        0,
        468,
        -2157,
        UNUSED,
        UNUSED,
        UNUSED,
        1993,
        -461,
        -238,
        251,
        UNUSED,
        895,
        UNUSED,
        0,
        0,
        306,
        UNUSED,
        -340,
        UNUSED,
        UNUSED,
        1,
        0,
        1374,
        UNUSED,
        -194,
        0,
        2354,
        656,
        1054,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -524,
        -3,
        -689,
        0,
        103,
        0,
        0,
        UNUSED,
        UNUSED,
        136,
        UNUSED,
        UNUSED,
        -159,
        3560,
        UNUSED,
        1019,
        UNUSED,
        0,
        UNUSED,
        -66,
        1013,
        UNUSED,
        873,
        115,
        0,
        1389,
        542,
        UNUSED,
        -275,
        UNUSED,
        51,
        1673,
        UNUSED,
        643,
        UNUSED,
        552,
        1061,
        UNUSED,
        -308,
        UNUSED,
        -2447,
        0,
        -181,
        0,
        0,
        32,
        0,
        UNUSED,
        0,
        234,
        1696,
        1032,
        271,
        UNUSED,
        UNUSED,
        0,
        984,
        2128,
        0,
        0,
        597,
        705,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -698,
        UNUSED,
        193,
        UNUSED,
        UNUSED,
        UNUSED,
        -178,
        UNUSED,
        302,
        -775,
        0,
        667,
        -815,
        UNUSED,
        -842,
        -774,
        UNUSED,
        UNUSED,
        73,
        UNUSED,
        630,
        0,
        840,
        346,
        UNUSED,
        0,
        358,
        222,
        UNUSED,
        3041,
        -662,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        1353,
        672,
        UNUSED,
        1881,
        UNUSED,
        UNUSED,
        675,
        UNUSED,
        623,
        669,
        508,
        UNUSED,
        124,
        UNUSED,
        444,
        1163,
        840,
        -247,
        0,
        -523,
        1425,
        UNUSED,
        0,
        638,
        0,
        1084,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -470,
        0,
        381,
        -1053,
        1046,
        505,
        618,
        UNUSED,
        0,
        4200,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        450,
        -496,
        919,
        UNUSED,
        -702,
        1014,
        662,
        402,
        0,
        UNUSED,
        -501,
        UNUSED,
        UNUSED,
        666,
        UNUSED,
        204,
        UNUSED,
        166,
        -334,
        UNUSED,
        687,
        721,
        1251,
        190,
        UNUSED,
        UNUSED,
        0,
        -841,
        918,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        345,
        UNUSED,
        -2090,
        -984,
        1803,
        439,
        1405,
        263,
        576,
        0,
        -1076,
        UNUSED,
        203,
        0,
        UNUSED,
        658,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -1072,
        -398,
        UNUSED,
        UNUSED,
        1025,
        1562,
        -920,
        0,
        0,
        UNUSED,
        UNUSED,
        1060,
        876,
        -513,
        390,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        478,
        0,
        -526,
        UNUSED,
        390,
        1027,
        -1021,
        -92,
        478,
        UNUSED,
        241,
        403,
        0,
        1129,
        1870,
        -674,
        UNUSED,
        1515,
        909,
        UNUSED,
        901,
        557,
        717,
        132,
        UNUSED,
        -1227,
        -321,
        UNUSED,
        UNUSED,
        UNUSED,
        -364,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -3384,
        0,
        UNUSED,
        2392,
        UNUSED,
        UNUSED,
        UNUSED,
        -368,
        UNUSED,
        -2,
        1079,
        UNUSED,
        UNUSED,
        1069,
        556,
        2394,
        UNUSED,
        0,
        0,
        126,
        0,
        3006,
        UNUSED,
        0,
        28,
        -1100,
        134,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -489,
        587,
        927,
        UNUSED,
        332,
        UNUSED,
        -2166,
        -745,
        371,
        353,
        -208,
        1113,
        UNUSED,
        0,
        565,
        -1389,
        520,
        0,
        175,
        0,
        UNUSED,
        -1147,
        UNUSED,
        -477,
        -437,
        17,
        UNUSED,
        -85,
        1053,
        UNUSED,
        456,
        UNUSED,
        UNUSED,
        -1308,
        520,
        872,
        222,
        UNUSED,
        1135,
        UNUSED,
        UNUSED,
        332,
        UNUSED,
        835,
        221,
        852,
        UNUSED,
        -644,
        UNUSED,
        18,
        379,
        UNUSED,
        246,
        937,
        UNUSED,
        -281,
        UNUSED,
        -2106,
        -1259,
        -169,
        -2593,
        114,
        831,
        UNUSED,
        -1791,
        UNUSED,
        -43,
        UNUSED,
        UNUSED,
        0,
        1226,
        912,
        683,
        9,
        UNUSED,
        296,
        -1046,
        UNUSED,
        1216,
        -2346,
        271,
        640,
        699,
        60,
        227,
        1358,
        UNUSED,
        -467,
        UNUSED,
        UNUSED,
        -65,
        -56,
        431,
        1536,
        UNUSED,
        UNUSED,
        -525,
        1630,
        UNUSED,
        833,
        UNUSED,
        6,
        -32,
        0,
        UNUSED,
        1475,
        UNUSED,
        350,
        UNUSED,
        UNUSED,
        588,
        471,
        -862,
        916,
        0,
        UNUSED,
        720,
        723,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        34,
        843,
        270,
        971,
        UNUSED,
        103,
        -308,
        UNUSED,
        UNUSED,
        UNUSED,
        262,
        1035,
        UNUSED,
        -365,
        1344,
        UNUSED,
        3027,
        -4127,
        UNUSED,
        -843,
        UNUSED,
        52,
        UNUSED,
        1313,
        147,
        736,
        866,
        548,
        0,
        -1126,
        UNUSED,
        -2160,
        -592,
        0,
        729,
        -1535,
        442,
        UNUSED,
        469,
        -66,
        UNUSED,
        568,
        UNUSED,
        808,
        -307,
        UNUSED,
        -870,
        560,
        1148,
        UNUSED,
        3519,
        UNUSED,
        1466,
        0,
        0,
        1253,
        UNUSED,
        363,
        -155,
        1367,
        -386,
        UNUSED,
        0,
        230,
        UNUSED,
        0,
        -142,
        182,
        UNUSED,
        283,
        UNUSED,
        UNUSED,
        654,
        UNUSED,
        UNUSED,
        -712,
        957,
        UNUSED,
        UNUSED,
        -273,
        157,
        -780,
        UNUSED,
        UNUSED,
        508,
        1022,
        0,
        UNUSED,
        UNUSED,
        127,
        983,
        -609,
        UNUSED,
        UNUSED,
        40,
        1170,
        921,
        122,
        UNUSED,
        382,
        0,
        2352,
        UNUSED,
        655,
        55,
        441,
        204,
        -3858,
        UNUSED,
        UNUSED,
        577,
        768,
        1015,
        -741,
        172,
        1616,
        -271,
        91,
        408,
        -450,
        561,
        254,
        UNUSED,
        UNUSED,
        173,
        714,
        652,
        -2615,
        1083,
        UNUSED,
        -67,
        -302,
        -199,
        UNUSED,
        UNUSED,
        UNUSED,
        -614,
        UNUSED,
        1010,
        401,
        -120,
        2009,
        655,
        610,
        1738,
        -2454,
        UNUSED,
        859,
        299,
        UNUSED,
        -1820,
        1279,
        -309,
        455,
        297,
        736,
        583,
        -829,
        UNUSED,
        -349,
        -732,
        UNUSED,
        UNUSED,
        UNUSED,
        189,
        8,
        604,
        UNUSED,
        UNUSED,
        665,
        UNUSED,
        532,
        2707,
        UNUSED,
        370,
        506,
        187,
        UNUSED,
        UNUSED,
        -1597,
        UNUSED,
        284,
        1029,
        292,
        UNUSED,
        -2558,
        1023,
        39,
        UNUSED,
        UNUSED,
        1071,
        265,
        755,
        -67,
        UNUSED,
        UNUSED,
        510,
        -1324,
        1544,
        -351,
        UNUSED,
        UNUSED,
        -156,
        163,
        894,
        UNUSED,
        842,
        427,
        -419,
        864,
        -429,
        710,
        781,
        434,
        119,
        -126,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -931,
        UNUSED,
        UNUSED,
        778,
        735,
        UNUSED,
        UNUSED,
        UNUSED,
        140,
        129,
        UNUSED,
        298,
        1051,
        UNUSED,
        114,
        -90,
        -1271,
        1012,
        UNUSED,
        UNUSED,
        588,
        -59,
        UNUSED,
        875,
        UNUSED,
        UNUSED,
        UNUSED,
        172,
        643,
        UNUSED,
        597,
        UNUSED,
        UNUSED,
        1094,
        UNUSED,
        -435,
        UNUSED,
        469,
        UNUSED,
        98,
        430,
        537,
        UNUSED,
        1019,
        -1375,
        1216,
        130,
        919,
        590,
        1052,
        284,
        -851,
        UNUSED,
        -880,
        963,
        827,
        0,
        993,
        UNUSED,
        696,
        -592,
        2826,
        819,
        270,
        -589,
        UNUSED,
        1021,
        31,
        783,
        354,
        375,
        340,
        UNUSED,
        596,
        932,
        UNUSED,
        UNUSED,
        UNUSED,
        2551,
        UNUSED,
        132,
        UNUSED,
        708,
        1408,
        UNUSED,
        531,
        UNUSED,
        UNUSED,
        -2261,
        573,
        UNUSED,
        UNUSED,
        UNUSED,
        -120,
        -11,
        712,
        UNUSED,
        1466,
        -542,
        UNUSED,
        788,
        UNUSED,
        21,
        -1752,
        175,
        -128,
        503,
        598,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        469,
        907,
        UNUSED,
        UNUSED,
        870,
        91,
        -47,
        UNUSED,
        3299,
        UNUSED,
        UNUSED,
        UNUSED,
        145,
        1019,
        647,
        UNUSED,
        -2304,
        -421,
        UNUSED,
        -1878,
        693,
        -133,
        732,
        UNUSED,
        1113,
        1034,
        352,
        274,
        194,
        81,
        -1129,
        -695,
        UNUSED,
        -412,
        UNUSED,
        -893,
        112,
        941,
        -292,
        UNUSED,
        685,
        UNUSED,
        UNUSED,
        592,
        UNUSED,
        UNUSED,
        1433,
        2015,
        UNUSED,
    };
    static const int16_t hash2[1024] = {
        0,
        0,
        0,
        0,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        1444,
        0,
        2390,
        0,
        0,
        0,
        0,
        1078,
        UNUSED,
        496,
        0,
        0,
        0,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -620,
        212,
        0,
        0,
        -5,
        0,
        -1518,
        -395,
        UNUSED,
        1411,
        UNUSED,
        -1998,
        0,
        23,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -991,
        UNUSED,
        0,
        3177,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        766,
        0,
        397,
        1140,
        UNUSED,
        UNUSED,
        261,
        UNUSED,
        UNUSED,
        -710,
        0,
        UNUSED,
        588,
        1965,
        0,
        0,
        131,
        0,
        0,
        -528,
        488,
        -442,
        UNUSED,
        -1296,
        UNUSED,
        156,
        UNUSED,
        1449,
        1682,
        UNUSED,
        0,
        0,
        UNUSED,
        384,
        UNUSED,
        UNUSED,
        3531,
        -1482,
        UNUSED,
        763,
        UNUSED,
        UNUSED,
        1037,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        501,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        378,
        UNUSED,
        UNUSED,
        251,
        UNUSED,
        UNUSED,
        UNUSED,
        1106,
        0,
        -615,
        0,
        UNUSED,
        591,
        4038,
        UNUSED,
        UNUSED,
        0,
        63,
        UNUSED,
        0,
        619,
        -677,
        0,
        -889,
        -1650,
        UNUSED,
        -539,
        1734,
        0,
        -3,
        UNUSED,
        0,
        UNUSED,
        -1615,
        63,
        771,
        -108,
        UNUSED,
        400,
        UNUSED,
        UNUSED,
        -725,
        UNUSED,
        UNUSED,
        1097,
        UNUSED,
        UNUSED,
        920,
        748,
        UNUSED,
        UNUSED,
        725,
        167,
        0,
        107,
        1028,
        UNUSED,
        UNUSED,
        -363,
        -491,
        UNUSED,
        -265,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        439,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        68,
        UNUSED,
        128,
        -585,
        135,
        UNUSED,
        UNUSED,
        472,
        -290,
        0,
        0,
        279,
        UNUSED,
        0,
        -354,
        -1000,
        0,
        1339,
        1532,
        UNUSED,
        -408,
        UNUSED,
        413,
        1625,
        0,
        -472,
        0,
        UNUSED,
        875,
        -722,
        UNUSED,
        1048,
        UNUSED,
        1007,
        1131,
        607,
        1358,
        UNUSED,
        0,
        UNUSED,
        -1081,
        0,
        800,
        UNUSED,
        UNUSED,
        470,
        1275,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -585,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        -288,
        291,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -260,
        -350,
        UNUSED,
        129,
        1090,
        UNUSED,
        0,
        UNUSED,
        0,
        342,
        UNUSED,
        -207,
        -508,
        601,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1018,
        UNUSED,
        464,
        -311,
        0,
        UNUSED,
        0,
        -1050,
        0,
        1013,
        582,
        -161,
        -716,
        1311,
        UNUSED,
        UNUSED,
        -96,
        -2544,
        16,
        -272,
        0,
        UNUSED,
        0,
        816,
        UNUSED,
        906,
        UNUSED,
        3399,
        73,
        -1886,
        -126,
        UNUSED,
        0,
        UNUSED,
        0,
        282,
        732,
        UNUSED,
        0,
        UNUSED,
        842,
        722,
        UNUSED,
        UNUSED,
        UNUSED,
        -200,
        563,
        -554,
        1238,
        UNUSED,
        0,
        0,
        -1300,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        829,
        328,
        512,
        0,
        UNUSED,
        661,
        -3224,
        UNUSED,
        -1024,
        0,
        261,
        -101,
        -3,
        3055,
        946,
        0,
        -2221,
        848,
        -1166,
        1333,
        0,
        -1221,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        129,
        534,
        UNUSED,
        0,
        1018,
        -598,
        UNUSED,
        UNUSED,
        1082,
        UNUSED,
        659,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        2740,
        645,
        UNUSED,
        1261,
        UNUSED,
        427,
        3284,
        141,
        UNUSED,
        UNUSED,
        UNUSED,
        -891,
        UNUSED,
        622,
        329,
        UNUSED,
        -667,
        1944,
        UNUSED,
        800,
        UNUSED,
        699,
        624,
        71,
        3037,
        UNUSED,
        0,
        1500,
        280,
        2792,
        UNUSED,
        578,
        UNUSED,
        362,
        0,
        UNUSED,
        UNUSED,
        37,
        -190,
        UNUSED,
        577,
        UNUSED,
        0,
        2306,
        824,
        UNUSED,
        0,
        UNUSED,
        416,
        UNUSED,
        0,
        UNUSED,
        216,
        3086,
        -190,
        -1088,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1492,
        UNUSED,
        -609,
        190,
        UNUSED,
        0,
        -103,
        0,
        778,
        1464,
        UNUSED,
        131,
        4347,
        1247,
        UNUSED,
        2359,
        357,
        234,
        244,
        UNUSED,
        483,
        UNUSED,
        814,
        -1044,
        -3209,
        0,
        2021,
        UNUSED,
        -1472,
        -33,
        0,
        960,
        0,
        -3,
        256,
        -524,
        UNUSED,
        -1037,
        423,
        85,
        424,
        UNUSED,
        134,
        1881,
        692,
        -27,
        UNUSED,
        905,
        UNUSED,
        105,
        571,
        0,
        -906,
        133,
        -599,
        1155,
        UNUSED,
        UNUSED,
        -299,
        32,
        UNUSED,
        -232,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        594,
        0,
        UNUSED,
        219,
        UNUSED,
        -149,
        1536,
        UNUSED,
        UNUSED,
        935,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        912,
        296,
        549,
        217,
        UNUSED,
        348,
        0,
        2567,
        UNUSED,
        928,
        -740,
        -629,
        0,
        1753,
        0,
        1554,
        112,
        304,
        938,
        746,
        -663,
        UNUSED,
        117,
        UNUSED,
        971,
        1284,
        -1112,
        -474,
        -335,
        260,
        -141,
        UNUSED,
        UNUSED,
        -711,
        UNUSED,
        -2822,
        549,
        UNUSED,
        1411,
        792,
        1053,
        0,
        -65,
        144,
        0,
        UNUSED,
        313,
        350,
        UNUSED,
        UNUSED,
        982,
        UNUSED,
        0,
        -1927,
        446,
        UNUSED,
        UNUSED,
        -754,
        0,
        -556,
        0,
        888,
        975,
        UNUSED,
        UNUSED,
        UNUSED,
        -314,
        -1294,
        -512,
        792,
        0,
        -1192,
        UNUSED,
        488,
        UNUSED,
        2297,
        481,
        460,
        0,
        641,
        UNUSED,
        642,
        445,
        677,
        UNUSED,
        3021,
        1096,
        85,
        UNUSED,
        1239,
        UNUSED,
        -619,
        UNUSED,
        UNUSED,
        UNUSED,
        -2104,
        -94,
        705,
        UNUSED,
        UNUSED,
        240,
        -368,
        881,
        -579,
        303,
        46,
        UNUSED,
        UNUSED,
        26,
        UNUSED,
        1468,
        UNUSED,
        1703,
        104,
        UNUSED,
        1151,
        262,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -511,
        158,
        498,
        UNUSED,
        611,
        -414,
        1073,
        440,
        UNUSED,
        UNUSED,
        746,
        UNUSED,
        616,
        UNUSED,
        76,
        659,
        UNUSED,
        -1947,
        39,
        -711,
        -19,
        UNUSED,
        1847,
        0,
        UNUSED,
        327,
        UNUSED,
        UNUSED,
        621,
        0,
        0,
        2696,
        UNUSED,
        UNUSED,
        23,
        16,
        800,
        2748,
        462,
        837,
        3087,
        UNUSED,
        UNUSED,
        584,
        635,
        -494,
        1148,
        1002,
        UNUSED,
        UNUSED,
        80,
        -47,
        703,
        UNUSED,
        3029,
        -3471,
        965,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -622,
        709,
        461,
        0,
        UNUSED,
        955,
        618,
        UNUSED,
        954,
        UNUSED,
        UNUSED,
        926,
        98,
        769,
        -585,
        1652,
        -283,
        UNUSED,
        -139,
        -364,
        390,
        154,
        -21,
        190,
        -998,
        UNUSED,
        -289,
        514,
        -849,
        UNUSED,
        1249,
        3303,
        1765,
        -2279,
        328,
        132,
        77,
        922,
        UNUSED,
        2,
        0,
        437,
        UNUSED,
        UNUSED,
        UNUSED,
        429,
        UNUSED,
        263,
        UNUSED,
        UNUSED,
        UNUSED,
        1198,
        -3219,
        UNUSED,
        -95,
        0,
        -105,
        UNUSED,
        UNUSED,
        41,
        UNUSED,
        456,
        UNUSED,
        UNUSED,
        826,
        552,
        UNUSED,
        UNUSED,
        1057,
        628,
        UNUSED,
        456,
        82,
        459,
        2913,
        703,
        1227,
        604,
        288,
        165,
        952,
        286,
        610,
        329,
        792,
        UNUSED,
        UNUSED,
        1028,
        864,
        UNUSED,
        UNUSED,
        UNUSED,
        430,
        -125,
        UNUSED,
        533,
        154,
        270,
        417,
        UNUSED,
        931,
        574,
        867,
        546,
        -1424,
        417,
        644,
        UNUSED,
        416,
        -167,
        UNUSED,
        0,
        851,
        65,
        715,
        -1622,
        UNUSED,
        1069,
        UNUSED,
        -481,
        680,
        1082,
        UNUSED,
        -254,
        387,
        UNUSED,
        150,
        UNUSED,
        -569,
        UNUSED,
        167,
        -362,
        508,
        UNUSED,
        -1876,
        -305,
        UNUSED,
        639,
        947,
        -57,
        -384,
        773,
        UNUSED,
        1040,
        -171,
        297,
        323,
        UNUSED,
        -356,
        UNUSED,
        UNUSED,
        742,
        992,
        -803,
        UNUSED,
        573,
        0,
        UNUSED,
        135,
        407,
        UNUSED,
        1801,
        600,
        UNUSED,
        -473,
        UNUSED,
        UNUSED,
        782,
        -944,
        1293,
        60,
        891,
        -107,
        405,
        UNUSED,
        UNUSED,
        789,
        UNUSED,
        UNUSED,
        UNUSED,
        318,
        935,
        602,
        848,
        1265,
        824,
        -539,
        UNUSED,
        676,
        UNUSED,
        -451,
        997,
        UNUSED,
        -604,
        -826,
        292,
        -85,
        UNUSED,
        2580,
        1039,
        484,
        -832,
        -2323,
        579,
        897,
        81,
        916,
        239,
        UNUSED,
        4899,
        UNUSED,
        -970,
        677,
        1104,
        -355,
        2126,
        -184,
        849,
        -702,
        521,
        687,
        884,
        87,
        125,
        991,
        UNUSED,
        81,
        -168,
        UNUSED,
        UNUSED,
        -1630,
        UNUSED,
        1023,
        429,
        29,
        250,
        -961,
        UNUSED,
        2513,
        815,
        1861,
        -419,
        UNUSED,
        -3240,
        UNUSED,
        463,
        94,
        1464,
        UNUSED,
        UNUSED,
        UNUSED,
        74,
        UNUSED,
        0,
        369,
        UNUSED,
        -315,
        421,
        733,
        509,
        UNUSED,
        418,
        382,
        54,
        818,
        205,
        799,
        UNUSED,
        UNUSED,
        -203,
        -513,
        -16,
        -955,
        UNUSED,
        148,
        UNUSED,
        1104,
        UNUSED,
        -359,
        1251,
        UNUSED,
        2707,
        -358,
        UNUSED,
        1061,
        169,
        -76,
        1769,
        729,
        253,
        UNUSED,
        -426,
        -536,
        UNUSED,
        232,
        UNUSED,
        -1542,
        UNUSED,
        415,
        1471,
        276,
        20,
        311,
        798,
        UNUSED,
        769,
        496,
        367,
        2693,
        UNUSED,
        UNUSED,
        600,
        UNUSED,
        UNUSED,
        864,
        UNUSED,
        -418,
        -163,
        50,
        181,
        1763,
        3424,
    };
    static const struct tokendata tokendata[1102] = {
        { "db", TOKEN_INSN, C_none, I_DB },
        { "dw", TOKEN_INSN, C_none, I_DW },
        { "dd", TOKEN_INSN, C_none, I_DD },
        { "dq", TOKEN_INSN, C_none, I_DQ },
        { "dt", TOKEN_INSN, C_none, I_DT },
        { "do", TOKEN_INSN, C_none, I_DO },
        { "resb", TOKEN_INSN, C_none, I_RESB },
        { "resw", TOKEN_INSN, C_none, I_RESW },
        { "resd", TOKEN_INSN, C_none, I_RESD },
        { "resq", TOKEN_INSN, C_none, I_RESQ },
        { "rest", TOKEN_INSN, C_none, I_REST },
        { "reso", TOKEN_INSN, C_none, I_RESO },
        { "aaa", TOKEN_INSN, C_none, I_AAA },
        { "aad", TOKEN_INSN, C_none, I_AAD },
        { "aam", TOKEN_INSN, C_none, I_AAM },
        { "aas", TOKEN_INSN, C_none, I_AAS },
        { "adc", TOKEN_INSN, C_none, I_ADC },
        { "add", TOKEN_INSN, C_none, I_ADD },
        { "and", TOKEN_INSN, C_none, I_AND },
        { "arpl", TOKEN_INSN, C_none, I_ARPL },
        { "bb0_reset", TOKEN_INSN, C_none, I_BB0_RESET },
        { "bb1_reset", TOKEN_INSN, C_none, I_BB1_RESET },
        { "bound", TOKEN_INSN, C_none, I_BOUND },
        { "bsf", TOKEN_INSN, C_none, I_BSF },
        { "bsr", TOKEN_INSN, C_none, I_BSR },
        { "bswap", TOKEN_INSN, C_none, I_BSWAP },
        { "bt", TOKEN_INSN, C_none, I_BT },
        { "btc", TOKEN_INSN, C_none, I_BTC },
        { "btr", TOKEN_INSN, C_none, I_BTR },
        { "bts", TOKEN_INSN, C_none, I_BTS },
        { "call", TOKEN_INSN, C_none, I_CALL },
        { "cbw", TOKEN_INSN, C_none, I_CBW },
        { "cdq", TOKEN_INSN, C_none, I_CDQ },
        { "cdqe", TOKEN_INSN, C_none, I_CDQE },
        { "clc", TOKEN_INSN, C_none, I_CLC },
        { "cld", TOKEN_INSN, C_none, I_CLD },
        { "clflush", TOKEN_INSN, C_none, I_CLFLUSH },
        { "clgi", TOKEN_INSN, C_none, I_CLGI },
        { "cli", TOKEN_INSN, C_none, I_CLI },
        { "clts", TOKEN_INSN, C_none, I_CLTS },
        { "cmc", TOKEN_INSN, C_none, I_CMC },
        { "cmp", TOKEN_INSN, C_none, I_CMP },
        { "cmpsb", TOKEN_INSN, C_none, I_CMPSB },
        { "cmpsd", TOKEN_INSN, C_none, I_CMPSD },
        { "cmpsq", TOKEN_INSN, C_none, I_CMPSQ },
        { "cmpsw", TOKEN_INSN, C_none, I_CMPSW },
        { "cmpxchg", TOKEN_INSN, C_none, I_CMPXCHG },
        { "cmpxchg486", TOKEN_INSN, C_none, I_CMPXCHG486 },
        { "cmpxchg8b", TOKEN_INSN, C_none, I_CMPXCHG8B },
        { "cmpxchg16b", TOKEN_INSN, C_none, I_CMPXCHG16B },
        { "cpuid", TOKEN_INSN, C_none, I_CPUID },
        { "cpu_read", TOKEN_INSN, C_none, I_CPU_READ },
        { "cpu_write", TOKEN_INSN, C_none, I_CPU_WRITE },
        { "cqo", TOKEN_INSN, C_none, I_CQO },
        { "cwd", TOKEN_INSN, C_none, I_CWD },
        { "cwde", TOKEN_INSN, C_none, I_CWDE },
        { "daa", TOKEN_INSN, C_none, I_DAA },
        { "das", TOKEN_INSN, C_none, I_DAS },
        { "dec", TOKEN_INSN, C_none, I_DEC },
        { "div", TOKEN_INSN, C_none, I_DIV },
        { "dmint", TOKEN_INSN, C_none, I_DMINT },
        { "emms", TOKEN_INSN, C_none, I_EMMS },
        { "enter", TOKEN_INSN, C_none, I_ENTER },
        { "equ", TOKEN_INSN, C_none, I_EQU },
        { "f2xm1", TOKEN_INSN, C_none, I_F2XM1 },
        { "fabs", TOKEN_INSN, C_none, I_FABS },
        { "fadd", TOKEN_INSN, C_none, I_FADD },
        { "faddp", TOKEN_INSN, C_none, I_FADDP },
        { "fbld", TOKEN_INSN, C_none, I_FBLD },
        { "fbstp", TOKEN_INSN, C_none, I_FBSTP },
        { "fchs", TOKEN_INSN, C_none, I_FCHS },
        { "fclex", TOKEN_INSN, C_none, I_FCLEX },
        { "fcmovb", TOKEN_INSN, C_none, I_FCMOVB },
        { "fcmovbe", TOKEN_INSN, C_none, I_FCMOVBE },
        { "fcmove", TOKEN_INSN, C_none, I_FCMOVE },
        { "fcmovnb", TOKEN_INSN, C_none, I_FCMOVNB },
        { "fcmovnbe", TOKEN_INSN, C_none, I_FCMOVNBE },
        { "fcmovne", TOKEN_INSN, C_none, I_FCMOVNE },
        { "fcmovnu", TOKEN_INSN, C_none, I_FCMOVNU },
        { "fcmovu", TOKEN_INSN, C_none, I_FCMOVU },
        { "fcom", TOKEN_INSN, C_none, I_FCOM },
        { "fcomi", TOKEN_INSN, C_none, I_FCOMI },
        { "fcomip", TOKEN_INSN, C_none, I_FCOMIP },
        { "fcomp", TOKEN_INSN, C_none, I_FCOMP },
        { "fcompp", TOKEN_INSN, C_none, I_FCOMPP },
        { "fcos", TOKEN_INSN, C_none, I_FCOS },
        { "fdecstp", TOKEN_INSN, C_none, I_FDECSTP },
        { "fdisi", TOKEN_INSN, C_none, I_FDISI },
        { "fdiv", TOKEN_INSN, C_none, I_FDIV },
        { "fdivp", TOKEN_INSN, C_none, I_FDIVP },
        { "fdivr", TOKEN_INSN, C_none, I_FDIVR },
        { "fdivrp", TOKEN_INSN, C_none, I_FDIVRP },
        { "femms", TOKEN_INSN, C_none, I_FEMMS },
        { "feni", TOKEN_INSN, C_none, I_FENI },
        { "ffree", TOKEN_INSN, C_none, I_FFREE },
        { "ffreep", TOKEN_INSN, C_none, I_FFREEP },
        { "fiadd", TOKEN_INSN, C_none, I_FIADD },
        { "ficom", TOKEN_INSN, C_none, I_FICOM },
        { "ficomp", TOKEN_INSN, C_none, I_FICOMP },
        { "fidiv", TOKEN_INSN, C_none, I_FIDIV },
        { "fidivr", TOKEN_INSN, C_none, I_FIDIVR },
        { "fild", TOKEN_INSN, C_none, I_FILD },
        { "fimul", TOKEN_INSN, C_none, I_FIMUL },
        { "fincstp", TOKEN_INSN, C_none, I_FINCSTP },
        { "finit", TOKEN_INSN, C_none, I_FINIT },
        { "fist", TOKEN_INSN, C_none, I_FIST },
        { "fistp", TOKEN_INSN, C_none, I_FISTP },
        { "fisttp", TOKEN_INSN, C_none, I_FISTTP },
        { "fisub", TOKEN_INSN, C_none, I_FISUB },
        { "fisubr", TOKEN_INSN, C_none, I_FISUBR },
        { "fld", TOKEN_INSN, C_none, I_FLD },
        { "fld1", TOKEN_INSN, C_none, I_FLD1 },
        { "fldcw", TOKEN_INSN, C_none, I_FLDCW },
        { "fldenv", TOKEN_INSN, C_none, I_FLDENV },
        { "fldl2e", TOKEN_INSN, C_none, I_FLDL2E },
        { "fldl2t", TOKEN_INSN, C_none, I_FLDL2T },
        { "fldlg2", TOKEN_INSN, C_none, I_FLDLG2 },
        { "fldln2", TOKEN_INSN, C_none, I_FLDLN2 },
        { "fldpi", TOKEN_INSN, C_none, I_FLDPI },
        { "fldz", TOKEN_INSN, C_none, I_FLDZ },
        { "fmul", TOKEN_INSN, C_none, I_FMUL },
        { "fmulp", TOKEN_INSN, C_none, I_FMULP },
        { "fnclex", TOKEN_INSN, C_none, I_FNCLEX },
        { "fndisi", TOKEN_INSN, C_none, I_FNDISI },
        { "fneni", TOKEN_INSN, C_none, I_FNENI },
        { "fninit", TOKEN_INSN, C_none, I_FNINIT },
        { "fnop", TOKEN_INSN, C_none, I_FNOP },
        { "fnsave", TOKEN_INSN, C_none, I_FNSAVE },
        { "fnstcw", TOKEN_INSN, C_none, I_FNSTCW },
        { "fnstenv", TOKEN_INSN, C_none, I_FNSTENV },
        { "fnstsw", TOKEN_INSN, C_none, I_FNSTSW },
        { "fpatan", TOKEN_INSN, C_none, I_FPATAN },
        { "fprem", TOKEN_INSN, C_none, I_FPREM },
        { "fprem1", TOKEN_INSN, C_none, I_FPREM1 },
        { "fptan", TOKEN_INSN, C_none, I_FPTAN },
        { "frndint", TOKEN_INSN, C_none, I_FRNDINT },
        { "frstor", TOKEN_INSN, C_none, I_FRSTOR },
        { "fsave", TOKEN_INSN, C_none, I_FSAVE },
        { "fscale", TOKEN_INSN, C_none, I_FSCALE },
        { "fsetpm", TOKEN_INSN, C_none, I_FSETPM },
        { "fsin", TOKEN_INSN, C_none, I_FSIN },
        { "fsincos", TOKEN_INSN, C_none, I_FSINCOS },
        { "fsqrt", TOKEN_INSN, C_none, I_FSQRT },
        { "fst", TOKEN_INSN, C_none, I_FST },
        { "fstcw", TOKEN_INSN, C_none, I_FSTCW },
        { "fstenv", TOKEN_INSN, C_none, I_FSTENV },
        { "fstp", TOKEN_INSN, C_none, I_FSTP },
        { "fstsw", TOKEN_INSN, C_none, I_FSTSW },
        { "fsub", TOKEN_INSN, C_none, I_FSUB },
        { "fsubp", TOKEN_INSN, C_none, I_FSUBP },
        { "fsubr", TOKEN_INSN, C_none, I_FSUBR },
        { "fsubrp", TOKEN_INSN, C_none, I_FSUBRP },
        { "ftst", TOKEN_INSN, C_none, I_FTST },
        { "fucom", TOKEN_INSN, C_none, I_FUCOM },
        { "fucomi", TOKEN_INSN, C_none, I_FUCOMI },
        { "fucomip", TOKEN_INSN, C_none, I_FUCOMIP },
        { "fucomp", TOKEN_INSN, C_none, I_FUCOMP },
        { "fucompp", TOKEN_INSN, C_none, I_FUCOMPP },
        { "fxam", TOKEN_INSN, C_none, I_FXAM },
        { "fxch", TOKEN_INSN, C_none, I_FXCH },
        { "fxtract", TOKEN_INSN, C_none, I_FXTRACT },
        { "fyl2x", TOKEN_INSN, C_none, I_FYL2X },
        { "fyl2xp1", TOKEN_INSN, C_none, I_FYL2XP1 },
        { "hlt", TOKEN_INSN, C_none, I_HLT },
        { "ibts", TOKEN_INSN, C_none, I_IBTS },
        { "icebp", TOKEN_INSN, C_none, I_ICEBP },
        { "idiv", TOKEN_INSN, C_none, I_IDIV },
        { "imul", TOKEN_INSN, C_none, I_IMUL },
        { "in", TOKEN_INSN, C_none, I_IN },
        { "inc", TOKEN_INSN, C_none, I_INC },
        { "incbin", TOKEN_INSN, C_none, I_INCBIN },
        { "insb", TOKEN_INSN, C_none, I_INSB },
        { "insd", TOKEN_INSN, C_none, I_INSD },
        { "insw", TOKEN_INSN, C_none, I_INSW },
        { "int", TOKEN_INSN, C_none, I_INT },
        { "int01", TOKEN_INSN, C_none, I_INT01 },
        { "int1", TOKEN_INSN, C_none, I_INT1 },
        { "int03", TOKEN_INSN, C_none, I_INT03 },
        { "int3", TOKEN_INSN, C_none, I_INT3 },
        { "into", TOKEN_INSN, C_none, I_INTO },
        { "invd", TOKEN_INSN, C_none, I_INVD },
        { "invlpg", TOKEN_INSN, C_none, I_INVLPG },
        { "invlpga", TOKEN_INSN, C_none, I_INVLPGA },
        { "iret", TOKEN_INSN, C_none, I_IRET },
        { "iretd", TOKEN_INSN, C_none, I_IRETD },
        { "iretq", TOKEN_INSN, C_none, I_IRETQ },
        { "iretw", TOKEN_INSN, C_none, I_IRETW },
        { "jcxz", TOKEN_INSN, C_none, I_JCXZ },
        { "jecxz", TOKEN_INSN, C_none, I_JECXZ },
        { "jmp", TOKEN_INSN, C_none, I_JMP },
        { "jmpe", TOKEN_INSN, C_none, I_JMPE },
        { "jrcxz", TOKEN_INSN, C_none, I_JRCXZ },
        { "lahf", TOKEN_INSN, C_none, I_LAHF },
        { "lar", TOKEN_INSN, C_none, I_LAR },
        { "lds", TOKEN_INSN, C_none, I_LDS },
        { "lea", TOKEN_INSN, C_none, I_LEA },
        { "leave", TOKEN_INSN, C_none, I_LEAVE },
        { "les", TOKEN_INSN, C_none, I_LES },
        { "lfence", TOKEN_INSN, C_none, I_LFENCE },
        { "lfs", TOKEN_INSN, C_none, I_LFS },
        { "lgdt", TOKEN_INSN, C_none, I_LGDT },
        { "lgs", TOKEN_INSN, C_none, I_LGS },
        { "lidt", TOKEN_INSN, C_none, I_LIDT },
        { "lldt", TOKEN_INSN, C_none, I_LLDT },
        { "lmsw", TOKEN_INSN, C_none, I_LMSW },
        { "loadall", TOKEN_INSN, C_none, I_LOADALL },
        { "loadall286", TOKEN_INSN, C_none, I_LOADALL286 },
        { "lodsb", TOKEN_INSN, C_none, I_LODSB },
        { "lodsd", TOKEN_INSN, C_none, I_LODSD },
        { "lodsq", TOKEN_INSN, C_none, I_LODSQ },
        { "lodsw", TOKEN_INSN, C_none, I_LODSW },
        { "loop", TOKEN_INSN, C_none, I_LOOP },
        { "loope", TOKEN_INSN, C_none, I_LOOPE },
        { "loopne", TOKEN_INSN, C_none, I_LOOPNE },
        { "loopnz", TOKEN_INSN, C_none, I_LOOPNZ },
        { "loopz", TOKEN_INSN, C_none, I_LOOPZ },
        { "lsl", TOKEN_INSN, C_none, I_LSL },
        { "lss", TOKEN_INSN, C_none, I_LSS },
        { "ltr", TOKEN_INSN, C_none, I_LTR },
        { "mfence", TOKEN_INSN, C_none, I_MFENCE },
        { "monitor", TOKEN_INSN, C_none, I_MONITOR },
        { "mov", TOKEN_INSN, C_none, I_MOV },
        { "movd", TOKEN_INSN, C_none, I_MOVD },
        { "movq", TOKEN_INSN, C_none, I_MOVQ },
        { "movsb", TOKEN_INSN, C_none, I_MOVSB },
        { "movsd", TOKEN_INSN, C_none, I_MOVSD },
        { "movsq", TOKEN_INSN, C_none, I_MOVSQ },
        { "movsw", TOKEN_INSN, C_none, I_MOVSW },
        { "movsx", TOKEN_INSN, C_none, I_MOVSX },
        { "movzx", TOKEN_INSN, C_none, I_MOVZX },
        { "mul", TOKEN_INSN, C_none, I_MUL },
        { "mwait", TOKEN_INSN, C_none, I_MWAIT },
        { "neg", TOKEN_INSN, C_none, I_NEG },
        { "nop", TOKEN_INSN, C_none, I_NOP },
        { "not", TOKEN_INSN, C_none, I_NOT },
        { "or", TOKEN_INSN, C_none, I_OR },
        { "out", TOKEN_INSN, C_none, I_OUT },
        { "outsb", TOKEN_INSN, C_none, I_OUTSB },
        { "outsd", TOKEN_INSN, C_none, I_OUTSD },
        { "outsw", TOKEN_INSN, C_none, I_OUTSW },
        { "packssdw", TOKEN_INSN, C_none, I_PACKSSDW },
        { "packsswb", TOKEN_INSN, C_none, I_PACKSSWB },
        { "packuswb", TOKEN_INSN, C_none, I_PACKUSWB },
        { "paddb", TOKEN_INSN, C_none, I_PADDB },
        { "paddd", TOKEN_INSN, C_none, I_PADDD },
        { "paddsb", TOKEN_INSN, C_none, I_PADDSB },
        { "paddsiw", TOKEN_INSN, C_none, I_PADDSIW },
        { "paddsw", TOKEN_INSN, C_none, I_PADDSW },
        { "paddusb", TOKEN_INSN, C_none, I_PADDUSB },
        { "paddusw", TOKEN_INSN, C_none, I_PADDUSW },
        { "paddw", TOKEN_INSN, C_none, I_PADDW },
        { "pand", TOKEN_INSN, C_none, I_PAND },
        { "pandn", TOKEN_INSN, C_none, I_PANDN },
        { "pause", TOKEN_INSN, C_none, I_PAUSE },
        { "paveb", TOKEN_INSN, C_none, I_PAVEB },
        { "pavgusb", TOKEN_INSN, C_none, I_PAVGUSB },
        { "pcmpeqb", TOKEN_INSN, C_none, I_PCMPEQB },
        { "pcmpeqd", TOKEN_INSN, C_none, I_PCMPEQD },
        { "pcmpeqw", TOKEN_INSN, C_none, I_PCMPEQW },
        { "pcmpgtb", TOKEN_INSN, C_none, I_PCMPGTB },
        { "pcmpgtd", TOKEN_INSN, C_none, I_PCMPGTD },
        { "pcmpgtw", TOKEN_INSN, C_none, I_PCMPGTW },
        { "pdistib", TOKEN_INSN, C_none, I_PDISTIB },
        { "pf2id", TOKEN_INSN, C_none, I_PF2ID },
        { "pfacc", TOKEN_INSN, C_none, I_PFACC },
        { "pfadd", TOKEN_INSN, C_none, I_PFADD },
        { "pfcmpeq", TOKEN_INSN, C_none, I_PFCMPEQ },
        { "pfcmpge", TOKEN_INSN, C_none, I_PFCMPGE },
        { "pfcmpgt", TOKEN_INSN, C_none, I_PFCMPGT },
        { "pfmax", TOKEN_INSN, C_none, I_PFMAX },
        { "pfmin", TOKEN_INSN, C_none, I_PFMIN },
        { "pfmul", TOKEN_INSN, C_none, I_PFMUL },
        { "pfrcp", TOKEN_INSN, C_none, I_PFRCP },
        { "pfrcpit1", TOKEN_INSN, C_none, I_PFRCPIT1 },
        { "pfrcpit2", TOKEN_INSN, C_none, I_PFRCPIT2 },
        { "pfrsqit1", TOKEN_INSN, C_none, I_PFRSQIT1 },
        { "pfrsqrt", TOKEN_INSN, C_none, I_PFRSQRT },
        { "pfsub", TOKEN_INSN, C_none, I_PFSUB },
        { "pfsubr", TOKEN_INSN, C_none, I_PFSUBR },
        { "pi2fd", TOKEN_INSN, C_none, I_PI2FD },
        { "pmachriw", TOKEN_INSN, C_none, I_PMACHRIW },
        { "pmaddwd", TOKEN_INSN, C_none, I_PMADDWD },
        { "pmagw", TOKEN_INSN, C_none, I_PMAGW },
        { "pmulhriw", TOKEN_INSN, C_none, I_PMULHRIW },
        { "pmulhrwa", TOKEN_INSN, C_none, I_PMULHRWA },
        { "pmulhrwc", TOKEN_INSN, C_none, I_PMULHRWC },
        { "pmulhw", TOKEN_INSN, C_none, I_PMULHW },
        { "pmullw", TOKEN_INSN, C_none, I_PMULLW },
        { "pmvgezb", TOKEN_INSN, C_none, I_PMVGEZB },
        { "pmvlzb", TOKEN_INSN, C_none, I_PMVLZB },
        { "pmvnzb", TOKEN_INSN, C_none, I_PMVNZB },
        { "pmvzb", TOKEN_INSN, C_none, I_PMVZB },
        { "pop", TOKEN_INSN, C_none, I_POP },
        { "popa", TOKEN_INSN, C_none, I_POPA },
        { "popad", TOKEN_INSN, C_none, I_POPAD },
        { "popaw", TOKEN_INSN, C_none, I_POPAW },
        { "popf", TOKEN_INSN, C_none, I_POPF },
        { "popfd", TOKEN_INSN, C_none, I_POPFD },
        { "popfq", TOKEN_INSN, C_none, I_POPFQ },
        { "popfw", TOKEN_INSN, C_none, I_POPFW },
        { "por", TOKEN_INSN, C_none, I_POR },
        { "prefetch", TOKEN_INSN, C_none, I_PREFETCH },
        { "prefetchw", TOKEN_INSN, C_none, I_PREFETCHW },
        { "prefetchnta", TOKEN_INSN, C_none, I_PREFETCHNTA },
        { "prefetcht0", TOKEN_INSN, C_none, I_PREFETCHT0 },
        { "prefetcht1", TOKEN_INSN, C_none, I_PREFETCHT1 },
        { "prefetcht2", TOKEN_INSN, C_none, I_PREFETCHT2 },
        { "pslld", TOKEN_INSN, C_none, I_PSLLD },
        { "psllq", TOKEN_INSN, C_none, I_PSLLQ },
        { "psllw", TOKEN_INSN, C_none, I_PSLLW },
        { "psrad", TOKEN_INSN, C_none, I_PSRAD },
        { "psraw", TOKEN_INSN, C_none, I_PSRAW },
        { "psrld", TOKEN_INSN, C_none, I_PSRLD },
        { "psrlq", TOKEN_INSN, C_none, I_PSRLQ },
        { "psrlw", TOKEN_INSN, C_none, I_PSRLW },
        { "psubb", TOKEN_INSN, C_none, I_PSUBB },
        { "psubd", TOKEN_INSN, C_none, I_PSUBD },
        { "psubsb", TOKEN_INSN, C_none, I_PSUBSB },
        { "psubsiw", TOKEN_INSN, C_none, I_PSUBSIW },
        { "psubsw", TOKEN_INSN, C_none, I_PSUBSW },
        { "psubusb", TOKEN_INSN, C_none, I_PSUBUSB },
        { "psubusw", TOKEN_INSN, C_none, I_PSUBUSW },
        { "psubw", TOKEN_INSN, C_none, I_PSUBW },
        { "punpckhbw", TOKEN_INSN, C_none, I_PUNPCKHBW },
        { "punpckhdq", TOKEN_INSN, C_none, I_PUNPCKHDQ },
        { "punpckhwd", TOKEN_INSN, C_none, I_PUNPCKHWD },
        { "punpcklbw", TOKEN_INSN, C_none, I_PUNPCKLBW },
        { "punpckldq", TOKEN_INSN, C_none, I_PUNPCKLDQ },
        { "punpcklwd", TOKEN_INSN, C_none, I_PUNPCKLWD },
        { "push", TOKEN_INSN, C_none, I_PUSH },
        { "pusha", TOKEN_INSN, C_none, I_PUSHA },
        { "pushad", TOKEN_INSN, C_none, I_PUSHAD },
        { "pushaw", TOKEN_INSN, C_none, I_PUSHAW },
        { "pushf", TOKEN_INSN, C_none, I_PUSHF },
        { "pushfd", TOKEN_INSN, C_none, I_PUSHFD },
        { "pushfq", TOKEN_INSN, C_none, I_PUSHFQ },
        { "pushfw", TOKEN_INSN, C_none, I_PUSHFW },
        { "pxor", TOKEN_INSN, C_none, I_PXOR },
        { "rcl", TOKEN_INSN, C_none, I_RCL },
        { "rcr", TOKEN_INSN, C_none, I_RCR },
        { "rdshr", TOKEN_INSN, C_none, I_RDSHR },
        { "rdmsr", TOKEN_INSN, C_none, I_RDMSR },
        { "rdpmc", TOKEN_INSN, C_none, I_RDPMC },
        { "rdtsc", TOKEN_INSN, C_none, I_RDTSC },
        { "rdtscp", TOKEN_INSN, C_none, I_RDTSCP },
        { "ret", TOKEN_INSN, C_none, I_RET },
        { "retf", TOKEN_INSN, C_none, I_RETF },
        { "retn", TOKEN_INSN, C_none, I_RETN },
        { "rol", TOKEN_INSN, C_none, I_ROL },
        { "ror", TOKEN_INSN, C_none, I_ROR },
        { "rdm", TOKEN_INSN, C_none, I_RDM },
        { "rsdc", TOKEN_INSN, C_none, I_RSDC },
        { "rsldt", TOKEN_INSN, C_none, I_RSLDT },
        { "rsm", TOKEN_INSN, C_none, I_RSM },
        { "rsts", TOKEN_INSN, C_none, I_RSTS },
        { "sahf", TOKEN_INSN, C_none, I_SAHF },
        { "sal", TOKEN_INSN, C_none, I_SAL },
        { "salc", TOKEN_INSN, C_none, I_SALC },
        { "sar", TOKEN_INSN, C_none, I_SAR },
        { "sbb", TOKEN_INSN, C_none, I_SBB },
        { "scasb", TOKEN_INSN, C_none, I_SCASB },
        { "scasd", TOKEN_INSN, C_none, I_SCASD },
        { "scasq", TOKEN_INSN, C_none, I_SCASQ },
        { "scasw", TOKEN_INSN, C_none, I_SCASW },
        { "sfence", TOKEN_INSN, C_none, I_SFENCE },
        { "sgdt", TOKEN_INSN, C_none, I_SGDT },
        { "shl", TOKEN_INSN, C_none, I_SHL },
        { "shld", TOKEN_INSN, C_none, I_SHLD },
        { "shr", TOKEN_INSN, C_none, I_SHR },
        { "shrd", TOKEN_INSN, C_none, I_SHRD },
        { "sidt", TOKEN_INSN, C_none, I_SIDT },
        { "sldt", TOKEN_INSN, C_none, I_SLDT },
        { "skinit", TOKEN_INSN, C_none, I_SKINIT },
        { "smi", TOKEN_INSN, C_none, I_SMI },
        { "smint", TOKEN_INSN, C_none, I_SMINT },
        { "smintold", TOKEN_INSN, C_none, I_SMINTOLD },
        { "smsw", TOKEN_INSN, C_none, I_SMSW },
        { "stc", TOKEN_INSN, C_none, I_STC },
        { "std", TOKEN_INSN, C_none, I_STD },
        { "stgi", TOKEN_INSN, C_none, I_STGI },
        { "sti", TOKEN_INSN, C_none, I_STI },
        { "stosb", TOKEN_INSN, C_none, I_STOSB },
        { "stosd", TOKEN_INSN, C_none, I_STOSD },
        { "stosq", TOKEN_INSN, C_none, I_STOSQ },
        { "stosw", TOKEN_INSN, C_none, I_STOSW },
        { "str", TOKEN_INSN, C_none, I_STR },
        { "sub", TOKEN_INSN, C_none, I_SUB },
        { "svdc", TOKEN_INSN, C_none, I_SVDC },
        { "svldt", TOKEN_INSN, C_none, I_SVLDT },
        { "svts", TOKEN_INSN, C_none, I_SVTS },
        { "swapgs", TOKEN_INSN, C_none, I_SWAPGS },
        { "syscall", TOKEN_INSN, C_none, I_SYSCALL },
        { "sysenter", TOKEN_INSN, C_none, I_SYSENTER },
        { "sysexit", TOKEN_INSN, C_none, I_SYSEXIT },
        { "sysret", TOKEN_INSN, C_none, I_SYSRET },
        { "test", TOKEN_INSN, C_none, I_TEST },
        { "ud0", TOKEN_INSN, C_none, I_UD0 },
        { "ud1", TOKEN_INSN, C_none, I_UD1 },
        { "ud2", TOKEN_INSN, C_none, I_UD2 },
        { "umov", TOKEN_INSN, C_none, I_UMOV },
        { "verr", TOKEN_INSN, C_none, I_VERR },
        { "verw", TOKEN_INSN, C_none, I_VERW },
        { "wait", TOKEN_INSN, C_none, I_WAIT },
        { "fwait", TOKEN_INSN, C_none, I_FWAIT },
        { "wbinvd", TOKEN_INSN, C_none, I_WBINVD },
        { "wrshr", TOKEN_INSN, C_none, I_WRSHR },
        { "wrmsr", TOKEN_INSN, C_none, I_WRMSR },
        { "xadd", TOKEN_INSN, C_none, I_XADD },
        { "xbts", TOKEN_INSN, C_none, I_XBTS },
        { "xchg", TOKEN_INSN, C_none, I_XCHG },
        { "xlatb", TOKEN_INSN, C_none, I_XLATB },
        { "xlat", TOKEN_INSN, C_none, I_XLAT },
        { "xor", TOKEN_INSN, C_none, I_XOR },
        { "cmova", TOKEN_INSN, C_A, I_CMOVcc },
        { "cmovae", TOKEN_INSN, C_AE, I_CMOVcc },
        { "cmovb", TOKEN_INSN, C_B, I_CMOVcc },
        { "cmovbe", TOKEN_INSN, C_BE, I_CMOVcc },
        { "cmovc", TOKEN_INSN, C_C, I_CMOVcc },
        { "cmove", TOKEN_INSN, C_E, I_CMOVcc },
        { "cmovg", TOKEN_INSN, C_G, I_CMOVcc },
        { "cmovge", TOKEN_INSN, C_GE, I_CMOVcc },
        { "cmovl", TOKEN_INSN, C_L, I_CMOVcc },
        { "cmovle", TOKEN_INSN, C_LE, I_CMOVcc },
        { "cmovna", TOKEN_INSN, C_NA, I_CMOVcc },
        { "cmovnae", TOKEN_INSN, C_NAE, I_CMOVcc },
        { "cmovnb", TOKEN_INSN, C_NB, I_CMOVcc },
        { "cmovnbe", TOKEN_INSN, C_NBE, I_CMOVcc },
        { "cmovnc", TOKEN_INSN, C_NC, I_CMOVcc },
        { "cmovne", TOKEN_INSN, C_NE, I_CMOVcc },
        { "cmovng", TOKEN_INSN, C_NG, I_CMOVcc },
        { "cmovnge", TOKEN_INSN, C_NGE, I_CMOVcc },
        { "cmovnl", TOKEN_INSN, C_NL, I_CMOVcc },
        { "cmovnle", TOKEN_INSN, C_NLE, I_CMOVcc },
        { "cmovno", TOKEN_INSN, C_NO, I_CMOVcc },
        { "cmovnp", TOKEN_INSN, C_NP, I_CMOVcc },
        { "cmovns", TOKEN_INSN, C_NS, I_CMOVcc },
        { "cmovnz", TOKEN_INSN, C_NZ, I_CMOVcc },
        { "cmovo", TOKEN_INSN, C_O, I_CMOVcc },
        { "cmovp", TOKEN_INSN, C_P, I_CMOVcc },
        { "cmovpe", TOKEN_INSN, C_PE, I_CMOVcc },
        { "cmovpo", TOKEN_INSN, C_PO, I_CMOVcc },
        { "cmovs", TOKEN_INSN, C_S, I_CMOVcc },
        { "cmovz", TOKEN_INSN, C_Z, I_CMOVcc },
        { "ja", TOKEN_INSN, C_A, I_Jcc },
        { "jae", TOKEN_INSN, C_AE, I_Jcc },
        { "jb", TOKEN_INSN, C_B, I_Jcc },
        { "jbe", TOKEN_INSN, C_BE, I_Jcc },
        { "jc", TOKEN_INSN, C_C, I_Jcc },
        { "je", TOKEN_INSN, C_E, I_Jcc },
        { "jg", TOKEN_INSN, C_G, I_Jcc },
        { "jge", TOKEN_INSN, C_GE, I_Jcc },
        { "jl", TOKEN_INSN, C_L, I_Jcc },
        { "jle", TOKEN_INSN, C_LE, I_Jcc },
        { "jna", TOKEN_INSN, C_NA, I_Jcc },
        { "jnae", TOKEN_INSN, C_NAE, I_Jcc },
        { "jnb", TOKEN_INSN, C_NB, I_Jcc },
        { "jnbe", TOKEN_INSN, C_NBE, I_Jcc },
        { "jnc", TOKEN_INSN, C_NC, I_Jcc },
        { "jne", TOKEN_INSN, C_NE, I_Jcc },
        { "jng", TOKEN_INSN, C_NG, I_Jcc },
        { "jnge", TOKEN_INSN, C_NGE, I_Jcc },
        { "jnl", TOKEN_INSN, C_NL, I_Jcc },
        { "jnle", TOKEN_INSN, C_NLE, I_Jcc },
        { "jno", TOKEN_INSN, C_NO, I_Jcc },
        { "jnp", TOKEN_INSN, C_NP, I_Jcc },
        { "jns", TOKEN_INSN, C_NS, I_Jcc },
        { "jnz", TOKEN_INSN, C_NZ, I_Jcc },
        { "jo", TOKEN_INSN, C_O, I_Jcc },
        { "jp", TOKEN_INSN, C_P, I_Jcc },
        { "jpe", TOKEN_INSN, C_PE, I_Jcc },
        { "jpo", TOKEN_INSN, C_PO, I_Jcc },
        { "js", TOKEN_INSN, C_S, I_Jcc },
        { "jz", TOKEN_INSN, C_Z, I_Jcc },
        { "seta", TOKEN_INSN, C_A, I_SETcc },
        { "setae", TOKEN_INSN, C_AE, I_SETcc },
        { "setb", TOKEN_INSN, C_B, I_SETcc },
        { "setbe", TOKEN_INSN, C_BE, I_SETcc },
        { "setc", TOKEN_INSN, C_C, I_SETcc },
        { "sete", TOKEN_INSN, C_E, I_SETcc },
        { "setg", TOKEN_INSN, C_G, I_SETcc },
        { "setge", TOKEN_INSN, C_GE, I_SETcc },
        { "setl", TOKEN_INSN, C_L, I_SETcc },
        { "setle", TOKEN_INSN, C_LE, I_SETcc },
        { "setna", TOKEN_INSN, C_NA, I_SETcc },
        { "setnae", TOKEN_INSN, C_NAE, I_SETcc },
        { "setnb", TOKEN_INSN, C_NB, I_SETcc },
        { "setnbe", TOKEN_INSN, C_NBE, I_SETcc },
        { "setnc", TOKEN_INSN, C_NC, I_SETcc },
        { "setne", TOKEN_INSN, C_NE, I_SETcc },
        { "setng", TOKEN_INSN, C_NG, I_SETcc },
        { "setnge", TOKEN_INSN, C_NGE, I_SETcc },
        { "setnl", TOKEN_INSN, C_NL, I_SETcc },
        { "setnle", TOKEN_INSN, C_NLE, I_SETcc },
        { "setno", TOKEN_INSN, C_NO, I_SETcc },
        { "setnp", TOKEN_INSN, C_NP, I_SETcc },
        { "setns", TOKEN_INSN, C_NS, I_SETcc },
        { "setnz", TOKEN_INSN, C_NZ, I_SETcc },
        { "seto", TOKEN_INSN, C_O, I_SETcc },
        { "setp", TOKEN_INSN, C_P, I_SETcc },
        { "setpe", TOKEN_INSN, C_PE, I_SETcc },
        { "setpo", TOKEN_INSN, C_PO, I_SETcc },
        { "sets", TOKEN_INSN, C_S, I_SETcc },
        { "setz", TOKEN_INSN, C_Z, I_SETcc },
        { "addps", TOKEN_INSN, C_none, I_ADDPS },
        { "addss", TOKEN_INSN, C_none, I_ADDSS },
        { "andnps", TOKEN_INSN, C_none, I_ANDNPS },
        { "andps", TOKEN_INSN, C_none, I_ANDPS },
        { "cmpeqps", TOKEN_INSN, C_none, I_CMPEQPS },
        { "cmpeqss", TOKEN_INSN, C_none, I_CMPEQSS },
        { "cmpleps", TOKEN_INSN, C_none, I_CMPLEPS },
        { "cmpless", TOKEN_INSN, C_none, I_CMPLESS },
        { "cmpltps", TOKEN_INSN, C_none, I_CMPLTPS },
        { "cmpltss", TOKEN_INSN, C_none, I_CMPLTSS },
        { "cmpneqps", TOKEN_INSN, C_none, I_CMPNEQPS },
        { "cmpneqss", TOKEN_INSN, C_none, I_CMPNEQSS },
        { "cmpnleps", TOKEN_INSN, C_none, I_CMPNLEPS },
        { "cmpnless", TOKEN_INSN, C_none, I_CMPNLESS },
        { "cmpnltps", TOKEN_INSN, C_none, I_CMPNLTPS },
        { "cmpnltss", TOKEN_INSN, C_none, I_CMPNLTSS },
        { "cmpordps", TOKEN_INSN, C_none, I_CMPORDPS },
        { "cmpordss", TOKEN_INSN, C_none, I_CMPORDSS },
        { "cmpunordps", TOKEN_INSN, C_none, I_CMPUNORDPS },
        { "cmpunordss", TOKEN_INSN, C_none, I_CMPUNORDSS },
        { "cmpps", TOKEN_INSN, C_none, I_CMPPS },
        { "cmpss", TOKEN_INSN, C_none, I_CMPSS },
        { "comiss", TOKEN_INSN, C_none, I_COMISS },
        { "cvtpi2ps", TOKEN_INSN, C_none, I_CVTPI2PS },
        { "cvtps2pi", TOKEN_INSN, C_none, I_CVTPS2PI },
        { "cvtsi2ss", TOKEN_INSN, C_none, I_CVTSI2SS },
        { "cvtss2si", TOKEN_INSN, C_none, I_CVTSS2SI },
        { "cvttps2pi", TOKEN_INSN, C_none, I_CVTTPS2PI },
        { "cvttss2si", TOKEN_INSN, C_none, I_CVTTSS2SI },
        { "divps", TOKEN_INSN, C_none, I_DIVPS },
        { "divss", TOKEN_INSN, C_none, I_DIVSS },
        { "ldmxcsr", TOKEN_INSN, C_none, I_LDMXCSR },
        { "maxps", TOKEN_INSN, C_none, I_MAXPS },
        { "maxss", TOKEN_INSN, C_none, I_MAXSS },
        { "minps", TOKEN_INSN, C_none, I_MINPS },
        { "minss", TOKEN_INSN, C_none, I_MINSS },
        { "movaps", TOKEN_INSN, C_none, I_MOVAPS },
        { "movhps", TOKEN_INSN, C_none, I_MOVHPS },
        { "movlhps", TOKEN_INSN, C_none, I_MOVLHPS },
        { "movlps", TOKEN_INSN, C_none, I_MOVLPS },
        { "movhlps", TOKEN_INSN, C_none, I_MOVHLPS },
        { "movmskps", TOKEN_INSN, C_none, I_MOVMSKPS },
        { "movntps", TOKEN_INSN, C_none, I_MOVNTPS },
        { "movss", TOKEN_INSN, C_none, I_MOVSS },
        { "movups", TOKEN_INSN, C_none, I_MOVUPS },
        { "mulps", TOKEN_INSN, C_none, I_MULPS },
        { "mulss", TOKEN_INSN, C_none, I_MULSS },
        { "orps", TOKEN_INSN, C_none, I_ORPS },
        { "rcpps", TOKEN_INSN, C_none, I_RCPPS },
        { "rcpss", TOKEN_INSN, C_none, I_RCPSS },
        { "rsqrtps", TOKEN_INSN, C_none, I_RSQRTPS },
        { "rsqrtss", TOKEN_INSN, C_none, I_RSQRTSS },
        { "shufps", TOKEN_INSN, C_none, I_SHUFPS },
        { "sqrtps", TOKEN_INSN, C_none, I_SQRTPS },
        { "sqrtss", TOKEN_INSN, C_none, I_SQRTSS },
        { "stmxcsr", TOKEN_INSN, C_none, I_STMXCSR },
        { "subps", TOKEN_INSN, C_none, I_SUBPS },
        { "subss", TOKEN_INSN, C_none, I_SUBSS },
        { "ucomiss", TOKEN_INSN, C_none, I_UCOMISS },
        { "unpckhps", TOKEN_INSN, C_none, I_UNPCKHPS },
        { "unpcklps", TOKEN_INSN, C_none, I_UNPCKLPS },
        { "xorps", TOKEN_INSN, C_none, I_XORPS },
        { "fxrstor", TOKEN_INSN, C_none, I_FXRSTOR },
        { "fxsave", TOKEN_INSN, C_none, I_FXSAVE },
        { "maskmovq", TOKEN_INSN, C_none, I_MASKMOVQ },
        { "movntq", TOKEN_INSN, C_none, I_MOVNTQ },
        { "pavgb", TOKEN_INSN, C_none, I_PAVGB },
        { "pavgw", TOKEN_INSN, C_none, I_PAVGW },
        { "pextrw", TOKEN_INSN, C_none, I_PEXTRW },
        { "pinsrw", TOKEN_INSN, C_none, I_PINSRW },
        { "pmaxsw", TOKEN_INSN, C_none, I_PMAXSW },
        { "pmaxub", TOKEN_INSN, C_none, I_PMAXUB },
        { "pminsw", TOKEN_INSN, C_none, I_PMINSW },
        { "pminub", TOKEN_INSN, C_none, I_PMINUB },
        { "pmovmskb", TOKEN_INSN, C_none, I_PMOVMSKB },
        { "pmulhuw", TOKEN_INSN, C_none, I_PMULHUW },
        { "psadbw", TOKEN_INSN, C_none, I_PSADBW },
        { "pshufw", TOKEN_INSN, C_none, I_PSHUFW },
        { "pf2iw", TOKEN_INSN, C_none, I_PF2IW },
        { "pfnacc", TOKEN_INSN, C_none, I_PFNACC },
        { "pfpnacc", TOKEN_INSN, C_none, I_PFPNACC },
        { "pi2fw", TOKEN_INSN, C_none, I_PI2FW },
        { "pswapd", TOKEN_INSN, C_none, I_PSWAPD },
        { "maskmovdqu", TOKEN_INSN, C_none, I_MASKMOVDQU },
        { "movntdq", TOKEN_INSN, C_none, I_MOVNTDQ },
        { "movnti", TOKEN_INSN, C_none, I_MOVNTI },
        { "movntpd", TOKEN_INSN, C_none, I_MOVNTPD },
        { "movdqa", TOKEN_INSN, C_none, I_MOVDQA },
        { "movdqu", TOKEN_INSN, C_none, I_MOVDQU },
        { "movdq2q", TOKEN_INSN, C_none, I_MOVDQ2Q },
        { "movq2dq", TOKEN_INSN, C_none, I_MOVQ2DQ },
        { "paddq", TOKEN_INSN, C_none, I_PADDQ },
        { "pmuludq", TOKEN_INSN, C_none, I_PMULUDQ },
        { "pshufd", TOKEN_INSN, C_none, I_PSHUFD },
        { "pshufhw", TOKEN_INSN, C_none, I_PSHUFHW },
        { "pshuflw", TOKEN_INSN, C_none, I_PSHUFLW },
        { "pslldq", TOKEN_INSN, C_none, I_PSLLDQ },
        { "psrldq", TOKEN_INSN, C_none, I_PSRLDQ },
        { "psubq", TOKEN_INSN, C_none, I_PSUBQ },
        { "punpckhqdq", TOKEN_INSN, C_none, I_PUNPCKHQDQ },
        { "punpcklqdq", TOKEN_INSN, C_none, I_PUNPCKLQDQ },
        { "addpd", TOKEN_INSN, C_none, I_ADDPD },
        { "addsd", TOKEN_INSN, C_none, I_ADDSD },
        { "andnpd", TOKEN_INSN, C_none, I_ANDNPD },
        { "andpd", TOKEN_INSN, C_none, I_ANDPD },
        { "cmpeqpd", TOKEN_INSN, C_none, I_CMPEQPD },
        { "cmpeqsd", TOKEN_INSN, C_none, I_CMPEQSD },
        { "cmplepd", TOKEN_INSN, C_none, I_CMPLEPD },
        { "cmplesd", TOKEN_INSN, C_none, I_CMPLESD },
        { "cmpltpd", TOKEN_INSN, C_none, I_CMPLTPD },
        { "cmpltsd", TOKEN_INSN, C_none, I_CMPLTSD },
        { "cmpneqpd", TOKEN_INSN, C_none, I_CMPNEQPD },
        { "cmpneqsd", TOKEN_INSN, C_none, I_CMPNEQSD },
        { "cmpnlepd", TOKEN_INSN, C_none, I_CMPNLEPD },
        { "cmpnlesd", TOKEN_INSN, C_none, I_CMPNLESD },
        { "cmpnltpd", TOKEN_INSN, C_none, I_CMPNLTPD },
        { "cmpnltsd", TOKEN_INSN, C_none, I_CMPNLTSD },
        { "cmpordpd", TOKEN_INSN, C_none, I_CMPORDPD },
        { "cmpordsd", TOKEN_INSN, C_none, I_CMPORDSD },
        { "cmpunordpd", TOKEN_INSN, C_none, I_CMPUNORDPD },
        { "cmpunordsd", TOKEN_INSN, C_none, I_CMPUNORDSD },
        { "cmppd", TOKEN_INSN, C_none, I_CMPPD },
        { "comisd", TOKEN_INSN, C_none, I_COMISD },
        { "cvtdq2pd", TOKEN_INSN, C_none, I_CVTDQ2PD },
        { "cvtdq2ps", TOKEN_INSN, C_none, I_CVTDQ2PS },
        { "cvtpd2dq", TOKEN_INSN, C_none, I_CVTPD2DQ },
        { "cvtpd2pi", TOKEN_INSN, C_none, I_CVTPD2PI },
        { "cvtpd2ps", TOKEN_INSN, C_none, I_CVTPD2PS },
        { "cvtpi2pd", TOKEN_INSN, C_none, I_CVTPI2PD },
        { "cvtps2dq", TOKEN_INSN, C_none, I_CVTPS2DQ },
        { "cvtps2pd", TOKEN_INSN, C_none, I_CVTPS2PD },
        { "cvtsd2si", TOKEN_INSN, C_none, I_CVTSD2SI },
        { "cvtsd2ss", TOKEN_INSN, C_none, I_CVTSD2SS },
        { "cvtsi2sd", TOKEN_INSN, C_none, I_CVTSI2SD },
        { "cvtss2sd", TOKEN_INSN, C_none, I_CVTSS2SD },
        { "cvttpd2pi", TOKEN_INSN, C_none, I_CVTTPD2PI },
        { "cvttpd2dq", TOKEN_INSN, C_none, I_CVTTPD2DQ },
        { "cvttps2dq", TOKEN_INSN, C_none, I_CVTTPS2DQ },
        { "cvttsd2si", TOKEN_INSN, C_none, I_CVTTSD2SI },
        { "divpd", TOKEN_INSN, C_none, I_DIVPD },
        { "divsd", TOKEN_INSN, C_none, I_DIVSD },
        { "maxpd", TOKEN_INSN, C_none, I_MAXPD },
        { "maxsd", TOKEN_INSN, C_none, I_MAXSD },
        { "minpd", TOKEN_INSN, C_none, I_MINPD },
        { "minsd", TOKEN_INSN, C_none, I_MINSD },
        { "movapd", TOKEN_INSN, C_none, I_MOVAPD },
        { "movhpd", TOKEN_INSN, C_none, I_MOVHPD },
        { "movlpd", TOKEN_INSN, C_none, I_MOVLPD },
        { "movmskpd", TOKEN_INSN, C_none, I_MOVMSKPD },
        { "movupd", TOKEN_INSN, C_none, I_MOVUPD },
        { "mulpd", TOKEN_INSN, C_none, I_MULPD },
        { "mulsd", TOKEN_INSN, C_none, I_MULSD },
        { "orpd", TOKEN_INSN, C_none, I_ORPD },
        { "shufpd", TOKEN_INSN, C_none, I_SHUFPD },
        { "sqrtpd", TOKEN_INSN, C_none, I_SQRTPD },
        { "sqrtsd", TOKEN_INSN, C_none, I_SQRTSD },
        { "subpd", TOKEN_INSN, C_none, I_SUBPD },
        { "subsd", TOKEN_INSN, C_none, I_SUBSD },
        { "ucomisd", TOKEN_INSN, C_none, I_UCOMISD },
        { "unpckhpd", TOKEN_INSN, C_none, I_UNPCKHPD },
        { "unpcklpd", TOKEN_INSN, C_none, I_UNPCKLPD },
        { "xorpd", TOKEN_INSN, C_none, I_XORPD },
        { "addsubpd", TOKEN_INSN, C_none, I_ADDSUBPD },
        { "addsubps", TOKEN_INSN, C_none, I_ADDSUBPS },
        { "haddpd", TOKEN_INSN, C_none, I_HADDPD },
        { "haddps", TOKEN_INSN, C_none, I_HADDPS },
        { "hsubpd", TOKEN_INSN, C_none, I_HSUBPD },
        { "hsubps", TOKEN_INSN, C_none, I_HSUBPS },
        { "lddqu", TOKEN_INSN, C_none, I_LDDQU },
        { "movddup", TOKEN_INSN, C_none, I_MOVDDUP },
        { "movshdup", TOKEN_INSN, C_none, I_MOVSHDUP },
        { "movsldup", TOKEN_INSN, C_none, I_MOVSLDUP },
        { "vmcall", TOKEN_INSN, C_none, I_VMCALL },
        { "vmclear", TOKEN_INSN, C_none, I_VMCLEAR },
        { "vmlaunch", TOKEN_INSN, C_none, I_VMLAUNCH },
        { "vmload", TOKEN_INSN, C_none, I_VMLOAD },
        { "vmmcall", TOKEN_INSN, C_none, I_VMMCALL },
        { "vmptrld", TOKEN_INSN, C_none, I_VMPTRLD },
        { "vmptrst", TOKEN_INSN, C_none, I_VMPTRST },
        { "vmread", TOKEN_INSN, C_none, I_VMREAD },
        { "vmresume", TOKEN_INSN, C_none, I_VMRESUME },
        { "vmrun", TOKEN_INSN, C_none, I_VMRUN },
        { "vmsave", TOKEN_INSN, C_none, I_VMSAVE },
        { "vmwrite", TOKEN_INSN, C_none, I_VMWRITE },
        { "vmxoff", TOKEN_INSN, C_none, I_VMXOFF },
        { "vmxon", TOKEN_INSN, C_none, I_VMXON },
        { "pabsb", TOKEN_INSN, C_none, I_PABSB },
        { "pabsw", TOKEN_INSN, C_none, I_PABSW },
        { "pabsd", TOKEN_INSN, C_none, I_PABSD },
        { "palignr", TOKEN_INSN, C_none, I_PALIGNR },
        { "phaddw", TOKEN_INSN, C_none, I_PHADDW },
        { "phaddd", TOKEN_INSN, C_none, I_PHADDD },
        { "phaddsw", TOKEN_INSN, C_none, I_PHADDSW },
        { "phsubw", TOKEN_INSN, C_none, I_PHSUBW },
        { "phsubd", TOKEN_INSN, C_none, I_PHSUBD },
        { "phsubsw", TOKEN_INSN, C_none, I_PHSUBSW },
        { "pmaddubsw", TOKEN_INSN, C_none, I_PMADDUBSW },
        { "pmulhrsw", TOKEN_INSN, C_none, I_PMULHRSW },
        { "pshufb", TOKEN_INSN, C_none, I_PSHUFB },
        { "psignb", TOKEN_INSN, C_none, I_PSIGNB },
        { "psignw", TOKEN_INSN, C_none, I_PSIGNW },
        { "psignd", TOKEN_INSN, C_none, I_PSIGND },
        { "extrq", TOKEN_INSN, C_none, I_EXTRQ },
        { "insertq", TOKEN_INSN, C_none, I_INSERTQ },
        { "movntsd", TOKEN_INSN, C_none, I_MOVNTSD },
        { "movntss", TOKEN_INSN, C_none, I_MOVNTSS },
        { "lzcnt", TOKEN_INSN, C_none, I_LZCNT },
        { "blendpd", TOKEN_INSN, C_none, I_BLENDPD },
        { "blendps", TOKEN_INSN, C_none, I_BLENDPS },
        { "blendvpd", TOKEN_INSN, C_none, I_BLENDVPD },
        { "blendvps", TOKEN_INSN, C_none, I_BLENDVPS },
        { "dppd", TOKEN_INSN, C_none, I_DPPD },
        { "dpps", TOKEN_INSN, C_none, I_DPPS },
        { "extractps", TOKEN_INSN, C_none, I_EXTRACTPS },
        { "insertps", TOKEN_INSN, C_none, I_INSERTPS },
        { "movntdqa", TOKEN_INSN, C_none, I_MOVNTDQA },
        { "mpsadbw", TOKEN_INSN, C_none, I_MPSADBW },
        { "packusdw", TOKEN_INSN, C_none, I_PACKUSDW },
        { "pblendvb", TOKEN_INSN, C_none, I_PBLENDVB },
        { "pblendw", TOKEN_INSN, C_none, I_PBLENDW },
        { "pcmpeqq", TOKEN_INSN, C_none, I_PCMPEQQ },
        { "pextrb", TOKEN_INSN, C_none, I_PEXTRB },
        { "pextrd", TOKEN_INSN, C_none, I_PEXTRD },
        { "pextrq", TOKEN_INSN, C_none, I_PEXTRQ },
        { "phminposuw", TOKEN_INSN, C_none, I_PHMINPOSUW },
        { "pinsrb", TOKEN_INSN, C_none, I_PINSRB },
        { "pinsrd", TOKEN_INSN, C_none, I_PINSRD },
        { "pinsrq", TOKEN_INSN, C_none, I_PINSRQ },
        { "pmaxsb", TOKEN_INSN, C_none, I_PMAXSB },
        { "pmaxsd", TOKEN_INSN, C_none, I_PMAXSD },
        { "pmaxud", TOKEN_INSN, C_none, I_PMAXUD },
        { "pmaxuw", TOKEN_INSN, C_none, I_PMAXUW },
        { "pminsb", TOKEN_INSN, C_none, I_PMINSB },
        { "pminsd", TOKEN_INSN, C_none, I_PMINSD },
        { "pminud", TOKEN_INSN, C_none, I_PMINUD },
        { "pminuw", TOKEN_INSN, C_none, I_PMINUW },
        { "pmovsxbw", TOKEN_INSN, C_none, I_PMOVSXBW },
        { "pmovsxbd", TOKEN_INSN, C_none, I_PMOVSXBD },
        { "pmovsxbq", TOKEN_INSN, C_none, I_PMOVSXBQ },
        { "pmovsxwd", TOKEN_INSN, C_none, I_PMOVSXWD },
        { "pmovsxwq", TOKEN_INSN, C_none, I_PMOVSXWQ },
        { "pmovsxdq", TOKEN_INSN, C_none, I_PMOVSXDQ },
        { "pmovzxbw", TOKEN_INSN, C_none, I_PMOVZXBW },
        { "pmovzxbd", TOKEN_INSN, C_none, I_PMOVZXBD },
        { "pmovzxbq", TOKEN_INSN, C_none, I_PMOVZXBQ },
        { "pmovzxwd", TOKEN_INSN, C_none, I_PMOVZXWD },
        { "pmovzxwq", TOKEN_INSN, C_none, I_PMOVZXWQ },
        { "pmovzxdq", TOKEN_INSN, C_none, I_PMOVZXDQ },
        { "pmuldq", TOKEN_INSN, C_none, I_PMULDQ },
        { "pmulld", TOKEN_INSN, C_none, I_PMULLD },
        { "ptest", TOKEN_INSN, C_none, I_PTEST },
        { "roundpd", TOKEN_INSN, C_none, I_ROUNDPD },
        { "roundps", TOKEN_INSN, C_none, I_ROUNDPS },
        { "roundsd", TOKEN_INSN, C_none, I_ROUNDSD },
        { "roundss", TOKEN_INSN, C_none, I_ROUNDSS },
        { "crc32", TOKEN_INSN, C_none, I_CRC32 },
        { "pcmpestri", TOKEN_INSN, C_none, I_PCMPESTRI },
        { "pcmpestrm", TOKEN_INSN, C_none, I_PCMPESTRM },
        { "pcmpistri", TOKEN_INSN, C_none, I_PCMPISTRI },
        { "pcmpistrm", TOKEN_INSN, C_none, I_PCMPISTRM },
        { "pcmpgtq", TOKEN_INSN, C_none, I_PCMPGTQ },
        { "popcnt", TOKEN_INSN, C_none, I_POPCNT },
        { "fmaddps", TOKEN_INSN, C_none, I_FMADDPS },
        { "fmaddpd", TOKEN_INSN, C_none, I_FMADDPD },
        { "fmaddss", TOKEN_INSN, C_none, I_FMADDSS },
        { "fmaddsd", TOKEN_INSN, C_none, I_FMADDSD },
        { "fmsubps", TOKEN_INSN, C_none, I_FMSUBPS },
        { "fmsubpd", TOKEN_INSN, C_none, I_FMSUBPD },
        { "fmsubss", TOKEN_INSN, C_none, I_FMSUBSS },
        { "fmsubsd", TOKEN_INSN, C_none, I_FMSUBSD },
        { "fmnaddps", TOKEN_INSN, C_none, I_FMNADDPS },
        { "fmnaddpd", TOKEN_INSN, C_none, I_FMNADDPD },
        { "fmnaddss", TOKEN_INSN, C_none, I_FMNADDSS },
        { "fmnaddsd", TOKEN_INSN, C_none, I_FMNADDSD },
        { "fmnsubps", TOKEN_INSN, C_none, I_FMNSUBPS },
        { "fmnsubpd", TOKEN_INSN, C_none, I_FMNSUBPD },
        { "fmnsubss", TOKEN_INSN, C_none, I_FMNSUBSS },
        { "fmnsubsd", TOKEN_INSN, C_none, I_FMNSUBSD },
        { "comps", TOKEN_INSN, C_none, I_COMPS },
        { "compd", TOKEN_INSN, C_none, I_COMPD },
        { "comss", TOKEN_INSN, C_none, I_COMSS },
        { "comsd", TOKEN_INSN, C_none, I_COMSD },
        { "pcomb", TOKEN_INSN, C_none, I_PCOMB },
        { "pcomw", TOKEN_INSN, C_none, I_PCOMW },
        { "pcomd", TOKEN_INSN, C_none, I_PCOMD },
        { "pcomq", TOKEN_INSN, C_none, I_PCOMQ },
        { "pcomub", TOKEN_INSN, C_none, I_PCOMUB },
        { "pcomuw", TOKEN_INSN, C_none, I_PCOMUW },
        { "pcomud", TOKEN_INSN, C_none, I_PCOMUD },
        { "pcomuq", TOKEN_INSN, C_none, I_PCOMUQ },
        { "permps", TOKEN_INSN, C_none, I_PERMPS },
        { "permpd", TOKEN_INSN, C_none, I_PERMPD },
        { "pcmov", TOKEN_INSN, C_none, I_PCMOV },
        { "pperm", TOKEN_INSN, C_none, I_PPERM },
        { "pmacssww", TOKEN_INSN, C_none, I_PMACSSWW },
        { "pmacsww", TOKEN_INSN, C_none, I_PMACSWW },
        { "pmacsswd", TOKEN_INSN, C_none, I_PMACSSWD },
        { "pmacswd", TOKEN_INSN, C_none, I_PMACSWD },
        { "pmacssdd", TOKEN_INSN, C_none, I_PMACSSDD },
        { "pmacsdd", TOKEN_INSN, C_none, I_PMACSDD },
        { "pmacssdql", TOKEN_INSN, C_none, I_PMACSSDQL },
        { "pmacsdql", TOKEN_INSN, C_none, I_PMACSDQL },
        { "pmacssdqh", TOKEN_INSN, C_none, I_PMACSSDQH },
        { "pmacsdqh", TOKEN_INSN, C_none, I_PMACSDQH },
        { "pmadcsswd", TOKEN_INSN, C_none, I_PMADCSSWD },
        { "pmadcswd", TOKEN_INSN, C_none, I_PMADCSWD },
        { "protb", TOKEN_INSN, C_none, I_PROTB },
        { "protw", TOKEN_INSN, C_none, I_PROTW },
        { "protd", TOKEN_INSN, C_none, I_PROTD },
        { "protq", TOKEN_INSN, C_none, I_PROTQ },
        { "pshlb", TOKEN_INSN, C_none, I_PSHLB },
        { "pshlw", TOKEN_INSN, C_none, I_PSHLW },
        { "pshld", TOKEN_INSN, C_none, I_PSHLD },
        { "pshlq", TOKEN_INSN, C_none, I_PSHLQ },
        { "pshab", TOKEN_INSN, C_none, I_PSHAB },
        { "pshaw", TOKEN_INSN, C_none, I_PSHAW },
        { "pshad", TOKEN_INSN, C_none, I_PSHAD },
        { "pshaq", TOKEN_INSN, C_none, I_PSHAQ },
        { "frczps", TOKEN_INSN, C_none, I_FRCZPS },
        { "frczpd", TOKEN_INSN, C_none, I_FRCZPD },
        { "frczss", TOKEN_INSN, C_none, I_FRCZSS },
        { "frczsd", TOKEN_INSN, C_none, I_FRCZSD },
        { "cvtph2ps", TOKEN_INSN, C_none, I_CVTPH2PS },
        { "cvtps2ph", TOKEN_INSN, C_none, I_CVTPS2PH },
        { "phaddbw", TOKEN_INSN, C_none, I_PHADDBW },
        { "phaddbd", TOKEN_INSN, C_none, I_PHADDBD },
        { "phaddbq", TOKEN_INSN, C_none, I_PHADDBQ },
        { "phaddwd", TOKEN_INSN, C_none, I_PHADDWD },
        { "phaddwq", TOKEN_INSN, C_none, I_PHADDWQ },
        { "phadddq", TOKEN_INSN, C_none, I_PHADDDQ },
        { "phaddubw", TOKEN_INSN, C_none, I_PHADDUBW },
        { "phaddubd", TOKEN_INSN, C_none, I_PHADDUBD },
        { "phaddubq", TOKEN_INSN, C_none, I_PHADDUBQ },
        { "phadduwd", TOKEN_INSN, C_none, I_PHADDUWD },
        { "phadduwq", TOKEN_INSN, C_none, I_PHADDUWQ },
        { "phaddudq", TOKEN_INSN, C_none, I_PHADDUDQ },
        { "phsubbw", TOKEN_INSN, C_none, I_PHSUBBW },
        { "phsubwd", TOKEN_INSN, C_none, I_PHSUBWD },
        { "phsubdq", TOKEN_INSN, C_none, I_PHSUBDQ },
        { "getsec", TOKEN_INSN, C_none, I_GETSEC },
        { "xstore", TOKEN_INSN, C_none, I_XSTORE },
        { "xcryptecb", TOKEN_INSN, C_none, I_XCRYPTECB },
        { "xcryptcbc", TOKEN_INSN, C_none, I_XCRYPTCBC },
        { "xcryptcfb", TOKEN_INSN, C_none, I_XCRYPTCFB },
        { "xcryptofb", TOKEN_INSN, C_none, I_XCRYPTOFB },
        { "montmul", TOKEN_INSN, C_none, I_MONTMUL },
        { "xsha1", TOKEN_INSN, C_none, I_XSHA1 },
        { "xsha256", TOKEN_INSN, C_none, I_XSHA256 },
        { "hint_nop0", TOKEN_INSN, C_none, I_HINT_NOP0 },
        { "hint_nop1", TOKEN_INSN, C_none, I_HINT_NOP1 },
        { "hint_nop2", TOKEN_INSN, C_none, I_HINT_NOP2 },
        { "hint_nop3", TOKEN_INSN, C_none, I_HINT_NOP3 },
        { "hint_nop4", TOKEN_INSN, C_none, I_HINT_NOP4 },
        { "hint_nop5", TOKEN_INSN, C_none, I_HINT_NOP5 },
        { "hint_nop6", TOKEN_INSN, C_none, I_HINT_NOP6 },
        { "hint_nop7", TOKEN_INSN, C_none, I_HINT_NOP7 },
        { "hint_nop8", TOKEN_INSN, C_none, I_HINT_NOP8 },
        { "hint_nop9", TOKEN_INSN, C_none, I_HINT_NOP9 },
        { "hint_nop10", TOKEN_INSN, C_none, I_HINT_NOP10 },
        { "hint_nop11", TOKEN_INSN, C_none, I_HINT_NOP11 },
        { "hint_nop12", TOKEN_INSN, C_none, I_HINT_NOP12 },
        { "hint_nop13", TOKEN_INSN, C_none, I_HINT_NOP13 },
        { "hint_nop14", TOKEN_INSN, C_none, I_HINT_NOP14 },
        { "hint_nop15", TOKEN_INSN, C_none, I_HINT_NOP15 },
        { "hint_nop16", TOKEN_INSN, C_none, I_HINT_NOP16 },
        { "hint_nop17", TOKEN_INSN, C_none, I_HINT_NOP17 },
        { "hint_nop18", TOKEN_INSN, C_none, I_HINT_NOP18 },
        { "hint_nop19", TOKEN_INSN, C_none, I_HINT_NOP19 },
        { "hint_nop20", TOKEN_INSN, C_none, I_HINT_NOP20 },
        { "hint_nop21", TOKEN_INSN, C_none, I_HINT_NOP21 },
        { "hint_nop22", TOKEN_INSN, C_none, I_HINT_NOP22 },
        { "hint_nop23", TOKEN_INSN, C_none, I_HINT_NOP23 },
        { "hint_nop24", TOKEN_INSN, C_none, I_HINT_NOP24 },
        { "hint_nop25", TOKEN_INSN, C_none, I_HINT_NOP25 },
        { "hint_nop26", TOKEN_INSN, C_none, I_HINT_NOP26 },
        { "hint_nop27", TOKEN_INSN, C_none, I_HINT_NOP27 },
        { "hint_nop28", TOKEN_INSN, C_none, I_HINT_NOP28 },
        { "hint_nop29", TOKEN_INSN, C_none, I_HINT_NOP29 },
        { "hint_nop30", TOKEN_INSN, C_none, I_HINT_NOP30 },
        { "hint_nop31", TOKEN_INSN, C_none, I_HINT_NOP31 },
        { "hint_nop32", TOKEN_INSN, C_none, I_HINT_NOP32 },
        { "hint_nop33", TOKEN_INSN, C_none, I_HINT_NOP33 },
        { "hint_nop34", TOKEN_INSN, C_none, I_HINT_NOP34 },
        { "hint_nop35", TOKEN_INSN, C_none, I_HINT_NOP35 },
        { "hint_nop36", TOKEN_INSN, C_none, I_HINT_NOP36 },
        { "hint_nop37", TOKEN_INSN, C_none, I_HINT_NOP37 },
        { "hint_nop38", TOKEN_INSN, C_none, I_HINT_NOP38 },
        { "hint_nop39", TOKEN_INSN, C_none, I_HINT_NOP39 },
        { "hint_nop40", TOKEN_INSN, C_none, I_HINT_NOP40 },
        { "hint_nop41", TOKEN_INSN, C_none, I_HINT_NOP41 },
        { "hint_nop42", TOKEN_INSN, C_none, I_HINT_NOP42 },
        { "hint_nop43", TOKEN_INSN, C_none, I_HINT_NOP43 },
        { "hint_nop44", TOKEN_INSN, C_none, I_HINT_NOP44 },
        { "hint_nop45", TOKEN_INSN, C_none, I_HINT_NOP45 },
        { "hint_nop46", TOKEN_INSN, C_none, I_HINT_NOP46 },
        { "hint_nop47", TOKEN_INSN, C_none, I_HINT_NOP47 },
        { "hint_nop48", TOKEN_INSN, C_none, I_HINT_NOP48 },
        { "hint_nop49", TOKEN_INSN, C_none, I_HINT_NOP49 },
        { "hint_nop50", TOKEN_INSN, C_none, I_HINT_NOP50 },
        { "hint_nop51", TOKEN_INSN, C_none, I_HINT_NOP51 },
        { "hint_nop52", TOKEN_INSN, C_none, I_HINT_NOP52 },
        { "hint_nop53", TOKEN_INSN, C_none, I_HINT_NOP53 },
        { "hint_nop54", TOKEN_INSN, C_none, I_HINT_NOP54 },
        { "hint_nop55", TOKEN_INSN, C_none, I_HINT_NOP55 },
        { "hint_nop56", TOKEN_INSN, C_none, I_HINT_NOP56 },
        { "hint_nop57", TOKEN_INSN, C_none, I_HINT_NOP57 },
        { "hint_nop58", TOKEN_INSN, C_none, I_HINT_NOP58 },
        { "hint_nop59", TOKEN_INSN, C_none, I_HINT_NOP59 },
        { "hint_nop60", TOKEN_INSN, C_none, I_HINT_NOP60 },
        { "hint_nop61", TOKEN_INSN, C_none, I_HINT_NOP61 },
        { "hint_nop62", TOKEN_INSN, C_none, I_HINT_NOP62 },
        { "hint_nop63", TOKEN_INSN, C_none, I_HINT_NOP63 },
        { "al", TOKEN_REG, 0, R_AL },
        { "ah", TOKEN_REG, 0, R_AH },
        { "ax", TOKEN_REG, 0, R_AX },
        { "eax", TOKEN_REG, 0, R_EAX },
        { "rax", TOKEN_REG, 0, R_RAX },
        { "bl", TOKEN_REG, 0, R_BL },
        { "bh", TOKEN_REG, 0, R_BH },
        { "bx", TOKEN_REG, 0, R_BX },
        { "ebx", TOKEN_REG, 0, R_EBX },
        { "rbx", TOKEN_REG, 0, R_RBX },
        { "cl", TOKEN_REG, 0, R_CL },
        { "ch", TOKEN_REG, 0, R_CH },
        { "cx", TOKEN_REG, 0, R_CX },
        { "ecx", TOKEN_REG, 0, R_ECX },
        { "rcx", TOKEN_REG, 0, R_RCX },
        { "dl", TOKEN_REG, 0, R_DL },
        { "dh", TOKEN_REG, 0, R_DH },
        { "dx", TOKEN_REG, 0, R_DX },
        { "edx", TOKEN_REG, 0, R_EDX },
        { "rdx", TOKEN_REG, 0, R_RDX },
        { "spl", TOKEN_REG, 0, R_SPL },
        { "sp", TOKEN_REG, 0, R_SP },
        { "esp", TOKEN_REG, 0, R_ESP },
        { "rsp", TOKEN_REG, 0, R_RSP },
        { "bpl", TOKEN_REG, 0, R_BPL },
        { "bp", TOKEN_REG, 0, R_BP },
        { "ebp", TOKEN_REG, 0, R_EBP },
        { "rbp", TOKEN_REG, 0, R_RBP },
        { "sil", TOKEN_REG, 0, R_SIL },
        { "si", TOKEN_REG, 0, R_SI },
        { "esi", TOKEN_REG, 0, R_ESI },
        { "rsi", TOKEN_REG, 0, R_RSI },
        { "dil", TOKEN_REG, 0, R_DIL },
        { "di", TOKEN_REG, 0, R_DI },
        { "edi", TOKEN_REG, 0, R_EDI },
        { "rdi", TOKEN_REG, 0, R_RDI },
        { "r8b", TOKEN_REG, 0, R_R8B },
        { "r9b", TOKEN_REG, 0, R_R9B },
        { "r10b", TOKEN_REG, 0, R_R10B },
        { "r11b", TOKEN_REG, 0, R_R11B },
        { "r12b", TOKEN_REG, 0, R_R12B },
        { "r13b", TOKEN_REG, 0, R_R13B },
        { "r14b", TOKEN_REG, 0, R_R14B },
        { "r15b", TOKEN_REG, 0, R_R15B },
        { "r8w", TOKEN_REG, 0, R_R8W },
        { "r9w", TOKEN_REG, 0, R_R9W },
        { "r10w", TOKEN_REG, 0, R_R10W },
        { "r11w", TOKEN_REG, 0, R_R11W },
        { "r12w", TOKEN_REG, 0, R_R12W },
        { "r13w", TOKEN_REG, 0, R_R13W },
        { "r14w", TOKEN_REG, 0, R_R14W },
        { "r15w", TOKEN_REG, 0, R_R15W },
        { "r8d", TOKEN_REG, 0, R_R8D },
        { "r9d", TOKEN_REG, 0, R_R9D },
        { "r10d", TOKEN_REG, 0, R_R10D },
        { "r11d", TOKEN_REG, 0, R_R11D },
        { "r12d", TOKEN_REG, 0, R_R12D },
        { "r13d", TOKEN_REG, 0, R_R13D },
        { "r14d", TOKEN_REG, 0, R_R14D },
        { "r15d", TOKEN_REG, 0, R_R15D },
        { "r8", TOKEN_REG, 0, R_R8 },
        { "r9", TOKEN_REG, 0, R_R9 },
        { "r10", TOKEN_REG, 0, R_R10 },
        { "r11", TOKEN_REG, 0, R_R11 },
        { "r12", TOKEN_REG, 0, R_R12 },
        { "r13", TOKEN_REG, 0, R_R13 },
        { "r14", TOKEN_REG, 0, R_R14 },
        { "r15", TOKEN_REG, 0, R_R15 },
        { "cs", TOKEN_REG, 0, R_CS },
        { "ds", TOKEN_REG, 0, R_DS },
        { "es", TOKEN_REG, 0, R_ES },
        { "ss", TOKEN_REG, 0, R_SS },
        { "fs", TOKEN_REG, 0, R_FS },
        { "gs", TOKEN_REG, 0, R_GS },
        { "segr6", TOKEN_REG, 0, R_SEGR6 },
        { "segr7", TOKEN_REG, 0, R_SEGR7 },
        { "cr0", TOKEN_REG, 0, R_CR0 },
        { "cr1", TOKEN_REG, 0, R_CR1 },
        { "cr2", TOKEN_REG, 0, R_CR2 },
        { "cr3", TOKEN_REG, 0, R_CR3 },
        { "cr4", TOKEN_REG, 0, R_CR4 },
        { "cr5", TOKEN_REG, 0, R_CR5 },
        { "cr6", TOKEN_REG, 0, R_CR6 },
        { "cr7", TOKEN_REG, 0, R_CR7 },
        { "cr8", TOKEN_REG, 0, R_CR8 },
        { "cr9", TOKEN_REG, 0, R_CR9 },
        { "cr10", TOKEN_REG, 0, R_CR10 },
        { "cr11", TOKEN_REG, 0, R_CR11 },
        { "cr12", TOKEN_REG, 0, R_CR12 },
        { "cr13", TOKEN_REG, 0, R_CR13 },
        { "cr14", TOKEN_REG, 0, R_CR14 },
        { "cr15", TOKEN_REG, 0, R_CR15 },
        { "dr0", TOKEN_REG, 0, R_DR0 },
        { "dr1", TOKEN_REG, 0, R_DR1 },
        { "dr2", TOKEN_REG, 0, R_DR2 },
        { "dr3", TOKEN_REG, 0, R_DR3 },
        { "dr4", TOKEN_REG, 0, R_DR4 },
        { "dr5", TOKEN_REG, 0, R_DR5 },
        { "dr6", TOKEN_REG, 0, R_DR6 },
        { "dr7", TOKEN_REG, 0, R_DR7 },
        { "dr8", TOKEN_REG, 0, R_DR8 },
        { "dr9", TOKEN_REG, 0, R_DR9 },
        { "dr10", TOKEN_REG, 0, R_DR10 },
        { "dr11", TOKEN_REG, 0, R_DR11 },
        { "dr12", TOKEN_REG, 0, R_DR12 },
        { "dr13", TOKEN_REG, 0, R_DR13 },
        { "dr14", TOKEN_REG, 0, R_DR14 },
        { "dr15", TOKEN_REG, 0, R_DR15 },
        { "tr0", TOKEN_REG, 0, R_TR0 },
        { "tr1", TOKEN_REG, 0, R_TR1 },
        { "tr2", TOKEN_REG, 0, R_TR2 },
        { "tr3", TOKEN_REG, 0, R_TR3 },
        { "tr4", TOKEN_REG, 0, R_TR4 },
        { "tr5", TOKEN_REG, 0, R_TR5 },
        { "tr6", TOKEN_REG, 0, R_TR6 },
        { "tr7", TOKEN_REG, 0, R_TR7 },
        { "st0", TOKEN_REG, 0, R_ST0 },
        { "st1", TOKEN_REG, 0, R_ST1 },
        { "st2", TOKEN_REG, 0, R_ST2 },
        { "st3", TOKEN_REG, 0, R_ST3 },
        { "st4", TOKEN_REG, 0, R_ST4 },
        { "st5", TOKEN_REG, 0, R_ST5 },
        { "st6", TOKEN_REG, 0, R_ST6 },
        { "st7", TOKEN_REG, 0, R_ST7 },
        { "mm0", TOKEN_REG, 0, R_MM0 },
        { "mm1", TOKEN_REG, 0, R_MM1 },
        { "mm2", TOKEN_REG, 0, R_MM2 },
        { "mm3", TOKEN_REG, 0, R_MM3 },
        { "mm4", TOKEN_REG, 0, R_MM4 },
        { "mm5", TOKEN_REG, 0, R_MM5 },
        { "mm6", TOKEN_REG, 0, R_MM6 },
        { "mm7", TOKEN_REG, 0, R_MM7 },
        { "xmm0", TOKEN_REG, 0, R_XMM0 },
        { "xmm1", TOKEN_REG, 0, R_XMM1 },
        { "xmm2", TOKEN_REG, 0, R_XMM2 },
        { "xmm3", TOKEN_REG, 0, R_XMM3 },
        { "xmm4", TOKEN_REG, 0, R_XMM4 },
        { "xmm5", TOKEN_REG, 0, R_XMM5 },
        { "xmm6", TOKEN_REG, 0, R_XMM6 },
        { "xmm7", TOKEN_REG, 0, R_XMM7 },
        { "xmm8", TOKEN_REG, 0, R_XMM8 },
        { "xmm9", TOKEN_REG, 0, R_XMM9 },
        { "xmm10", TOKEN_REG, 0, R_XMM10 },
        { "xmm11", TOKEN_REG, 0, R_XMM11 },
        { "xmm12", TOKEN_REG, 0, R_XMM12 },
        { "xmm13", TOKEN_REG, 0, R_XMM13 },
        { "xmm14", TOKEN_REG, 0, R_XMM14 },
        { "xmm15", TOKEN_REG, 0, R_XMM15 },
        { "a16", TOKEN_PREFIX, 0, P_A16 },
        { "a32", TOKEN_PREFIX, 0, P_A32 },
        { "lock", TOKEN_PREFIX, 0, P_LOCK },
        { "o16", TOKEN_PREFIX, 0, P_O16 },
        { "o32", TOKEN_PREFIX, 0, P_O32 },
        { "rep", TOKEN_PREFIX, 0, P_REP },
        { "repe", TOKEN_PREFIX, 0, P_REPE },
        { "repne", TOKEN_PREFIX, 0, P_REPNE },
        { "repnz", TOKEN_PREFIX, 0, P_REPNZ },
        { "repz", TOKEN_PREFIX, 0, P_REPZ },
        { "times", TOKEN_PREFIX, 0, P_TIMES },
        { "abs", TOKEN_SPECIAL, 0, S_ABS },
        { "byte", TOKEN_SPECIAL, 0, S_BYTE },
        { "dword", TOKEN_SPECIAL, 0, S_DWORD },
        { "far", TOKEN_SPECIAL, 0, S_FAR },
        { "long", TOKEN_SPECIAL, 0, S_LONG },
        { "near", TOKEN_SPECIAL, 0, S_NEAR },
        { "nosplit", TOKEN_SPECIAL, 0, S_NOSPLIT },
        { "oword", TOKEN_SPECIAL, 0, S_OWORD },
        { "qword", TOKEN_SPECIAL, 0, S_QWORD },
        { "rel", TOKEN_SPECIAL, 0, S_REL },
        { "short", TOKEN_SPECIAL, 0, S_SHORT },
        { "strict", TOKEN_SPECIAL, 0, S_STRICT },
        { "to", TOKEN_SPECIAL, 0, S_TO },
        { "tword", TOKEN_SPECIAL, 0, S_TWORD },
        { "word", TOKEN_SPECIAL, 0, S_WORD },
        { "__infinity__", TOKEN_FLOAT, 0, 0 },
        { "__nan__", TOKEN_FLOAT, 0, 0 },
        { "__qnan__", TOKEN_FLOAT, 0, 0 },
        { "__snan__", TOKEN_FLOAT, 0, 0 },
        { "__float16__", TOKEN_FLOATIZE, 0, FLOAT_16 },
        { "__float32__", TOKEN_FLOATIZE, 0, FLOAT_32 },
        { "__float64__", TOKEN_FLOATIZE, 0, FLOAT_64 },
        { "__float80m__", TOKEN_FLOATIZE, 0, FLOAT_80M },
        { "__float80e__", TOKEN_FLOATIZE, 0, FLOAT_80E },
        { "__float128l__", TOKEN_FLOATIZE, 0, FLOAT_128L },
        { "__float128h__", TOKEN_FLOATIZE, 0, FLOAT_128H },
        { "seg", TOKEN_SEG, 0, 0 },
        { "wrt", TOKEN_WRT, 0, 0 },
    };
    uint32_t k1, k2;
    uint64_t crc;
    uint16_t ix;
    const struct tokendata *data;

    crc = crc64(UINT64_C(0x51306ad6e87a75b2), token);
    k1 = (uint32_t)crc;
    k2 = (uint32_t)(crc >> 32);

    ix = hash1[k1 & 0x3ff] + hash2[k2 & 0x3ff];
    if (ix >= 1102)
        return tv->t_type = TOKEN_ID;

    data = &tokendata[ix];
    if (strcmp(data->string, token))
        return tv->t_type = TOKEN_ID;

    tv->t_integer = data->num;
    tv->t_inttwo  = data->aux;
    return tv->t_type = data->tokentype;
}
