#include "werkclass.hpp"
#include "kdoc.hpp"

WerkClass2 WerkClasses2[] =
{

  /****************************************************************************/

    {
      "Load"      ,0x01,KC_ANY,0,0,0x06001000,WERK_CLASS_COL_ALL,'l',
      "",
      "Edit_Misc_Load",
      "Init_Misc_Load",
      "Exec_Misc_Load",
      { KC_ANY },
      { KC_ANY },
    },
    {
      "Store"     ,0x02,KC_ANY,1,1,0x26000100,WERK_CLASS_COL_ALL,'s',
      "",
      "Edit_Misc_Store",
      "Init_Misc_Nop",
      "Exec_Misc_Nop",
      { KC_ANY },
      { 0 },
    },
    {
      "Nop"       ,0x03,KC_ANY,1,1,0x26000100,WERK_CLASS_COL_ALL,0,
      "",
      "Edit_Misc_Nop",
      "Init_Misc_Nop",
      "Exec_Misc_Nop",
      { KC_ANY },
      { 0 },
    },
    {
      "Unknown"   ,0x04,KC_ANY,1,1,0x24000100,WERK_CLASS_COL_HIDE,0,
      "",
      "Edit_Misc_Nop",
      "Init_Misc_Nop",
      "Exec_Misc_Nop",
      { KC_ANY },
      { 0 },
    },
    {
      "Time"      ,0x05,KC_ANY,1,1,0x24000100,WERK_CLASS_COL_ALL,0,
      "",
      "Edit_Misc_Nop",
      "Init_Misc_Nop",
      "Exec_Misc_Time",
      { KC_ANY },
      { 0 },
    },
    {
      "Event"     ,0x06,KC_ANY,1,1,0x00000101,WERK_CLASS_COL_ALL,0,
      "f",
      "Edit_Misc_Event",
      "Init_Misc_Event",
      "Exec_Misc_Event",
      { KC_ANY },
      { 0 },
    },
    {
      "Trigger"   ,0x07,KC_ANY,1,1,0x10101112,WERK_CLASS_COL_ALL,0,
      "ffiibffbfffffffffc",
      "Edit_Misc_Trigger",
      "Init_Misc_Trigger",
      "Exec_Misc_Trigger",
      { KC_ANY },
      { 0 },
    },
    {
      "Delay"     ,0x08,KC_ANY,1,1,0x20000107,WERK_CLASS_COL_ALL,0,
      "bbeeeee",
      "Edit_Misc_Delay",
      "Init_Misc_Nop",
      "Exec_Misc_Delay",
      { KC_ANY },
      { 0 },
    },
    {
      "If"        ,0x09,KC_ANY,1,2,0x20000202,WERK_CLASS_COL_ALL,0,
      "bb",
      "Edit_Misc_If",
      "Init_Misc_If",
      "Exec_Misc_If",
      { KC_ANY,KC_ANY },
      { 0 },
    },
    {
      "SetIf"     ,0x0a,KC_ANY,1,1,0x20000104,WERK_CLASS_COL_ALL,0,
      "bbbb",
      "Edit_Misc_SetIf",
      "Init_Misc_Nop",
      "Exec_Misc_SetIf",
      { KC_ANY },
      { 0 },
    },
    {
      "State"     ,0x0b,KC_ANY,1,1,0x20000105,WERK_CLASS_COL_ALL,0,
      "bbbbb",
      "Edit_Misc_State",
      "Init_Misc_Nop",
      "Exec_Misc_State",
      { KC_ANY },
      { 0 },
    },
    {
      "PlaySample"     ,0x0c,KC_ANY,1,1,0x20000107,WERK_CLASS_COL_ALL,0,
      "bbebeeg",
      "Edit_Misc_PlaySample",
      "Init_Misc_Nop",
      "Exec_Misc_PlaySample",
      { KC_ANY },
      { 0 },
    },
    {
      "Demo"           ,0x0d,KC_DEMO,1,KK_MAXINPUT,0x25000000,WERK_CLASS_COL_ADD,'d',
      "",
      "Edit_Misc_Demo",
      "Init_Misc_Demo",
      "Exec_Misc_Demo",
      { KC_ANY },
      { 0 },
    },
    {
      "Menu"     ,0x0e,KC_ANY,1,1,0x20000105,WERK_CLASS_COL_ALL,0,
      "bbb",
      "Edit_Misc_Menu",
      "Init_Misc_Nop",
      "Exec_Misc_Menu",
      { KC_ANY },
      { 0 },
    },
    {
      "Master Camera"           ,0x0f,KC_DEMO,0,0,0x0000000c,WERK_CLASS_COL_ADD,0,
      "ffffffff"  "ffff",
      "Edit_Misc_MasterCam",
      "Init_Misc_MasterCam",
      "Exec_Misc_MasterCam",
      { 0 },
      { 0 },
    },


    /****************************************************************************/

      {
        "KKriegerPara",0x10,KC_SCENE,0,1,0x24800139,WERK_CLASS_COL_NEW,0,
        "iiiiiiii"
        "iiiiiiiib"
        "ffffffffffff"
        "fff"
        "iiiiiiiiffffffffbbbbbbbb"
        "f",
        "Edit_KKrieger_Para",
        "Init_KKrieger_Para",
        "Exec_KKrieger_Para",
        { KC_SCENE },
        { 0 },
      },
      {
        "Monster",0x11,KC_SCENE,1,2,0x3410021d,WERK_CLASS_COL_NEW,0,
        "fffffffffb"
        "iiififfbff" "ffffff" "bib",
        "Edit_KKrieger_Monster",
        "Init_KKrieger_Monster",
        "Exec_KKrieger_Monster",
        { KC_SCENE,KC_SCENE },
        { KC_ANY },
      },
      {
        "KKriegerEvents",0x12,KC_SCENE,0,1,0x34008101,WERK_CLASS_COL_NEW,0,
        "b",
        "Edit_KKrieger_Events",
        "Init_KKrieger_Events",
        "Exec_KKrieger_Events",
        { KC_SCENE },
        { 0 },
      },
      {
        "Respawn",0x13,KC_SCENE,0,0,0x00000005,WERK_CLASS_COL_NEW,0,
        "fffbf",
        "Edit_KKrieger_Respawn",
        "Init_KKrieger_Respawn",
        "Exec_KKrieger_Respawn",
        { KC_SCENE },
        { 0 },
      },
      {
        "SplashDamage",0x14,KC_SCENE,0,0,0x00000003,WERK_CLASS_COL_NEW,0,
        "bff",
        "Edit_KKrieger_SplashDamage",
        "Init_KKrieger_SplashDamage",
        "Exec_KKrieger_SplashDamage",
        { KC_SCENE },
        { 0 },
      },
      {
        "MonsterFlags",0x15,KC_SCENE,1,1,0x20000103,WERK_CLASS_COL_NEW,0,
        "bbb",
        "Edit_KKrieger_MonsterFlags",
        "Init_KKrieger_MonsterFlags",
        "Exec_KKrieger_MonsterFlags",
        { KC_SCENE,KC_SCENE },
        { KC_ANY },
      },

      /****************************************************************************/

        {
          "Spline"        ,0x18,KC_SPLINE,0,0,0x40080000,WERK_CLASS_COL_ADD,0,
          "",
          "Edit_Misc_Spline",
          "Init_Misc_Spline",
          "Exec_Misc_Nop",
          { 0 },
          { 0 },
        },

        {
          "Shaker"        ,0x19,KC_SPLINE,1,1,0x40000111,WERK_CLASS_COL_ADD,0,
          "bffffffffffffffff",
          "Edit_Misc_Shaker",
          "Init_Misc_Shaker",
          "Exec_Misc_Nop",
          { KC_SPLINE },
          { 0 },
        },

        {
          "PipeSpline"    ,0x1a,KC_SPLINE,0,0,0x40080000,WERK_CLASS_COL_ADD,0,
          "",
          "Edit_Misc_PipeSpline",
          "Init_Misc_PipeSpline",
          "Exec_Misc_Nop",
          { 0 },
          { 0 },
        },

        {
          "MetaSpline"    ,0x1b,KC_SPLINE,1,8,0x00000808,WERK_CLASS_COL_ADD,0,
          "ffffffff",
          "Edit_Misc_MetaSpline",
          "Init_Misc_MetaSpline",
          "Exec_Misc_Nop",
          { KC_SPLINE,KC_SPLINE,KC_SPLINE,KC_SPLINE,KC_SPLINE,KC_SPLINE,KC_SPLINE,KC_SPLINE },
          { 0 },
        },



        /****************************************************************************/

          {
            "Flat"      ,0x21,KC_BITMAP,0,0,0x06000003,WERK_CLASS_COL_NEW,'f',
            "bbc",
            "Edit_Bitmap_Flat",
            "Bitmap_Flat",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },

          {
            "Perlin"    ,0x22,KC_BITMAP,0,0,0x0600000b,WERK_CLASS_COL_NEW,'p',
            "bbbbebbggcc",
            "Edit_Bitmap_Perlin",
            "Bitmap_Perlin",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Color"     ,0x23,KC_BITMAP,1,1,0x06000102,WERK_CLASS_COL_MOD,'C' | sKEYQ_SHIFT,
            "bc",
            "Edit_Bitmap_Color",
            "Bitmap_Color",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Merge"     ,0x24,KC_BITMAP,1,KK_MAXINPUT,0x07000001,WERK_CLASS_COL_ADD,'a',
            "b",
            "Edit_Bitmap_Merge",
            "Bitmap_Merge",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },

          {
            "Format"    ,0x25,KC_BITMAP,1,1,0x06000103,WERK_CLASS_COL_MOD,0,
            "bbb",
            "Edit_Bitmap_Format",
            "Bitmap_Format",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Render Target" ,0x26,KC_BITMAP,0,0,0x06000003,WERK_CLASS_COL_MOD,0,
            "bbb",
            "Edit_Bitmap_RenderTarget",
            "Bitmap_RenderTarget",
            "Exec_Misc_Nop",
            { 0 },
            { 0 },
          },
          {
            "GlowRectOld"  ,0x27,KC_BITMAP,1,1,0x0600010b,WERK_CLASS_COL_MOD,0,
            "eeeeeeceebb",
            "Edit_Bitmap_GlowRectOld",
            "Bitmap_GlowRect",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Dots"      ,0x28,KC_BITMAP,1,1,0x06000104,WERK_CLASS_COL_MOD,0,
            "ccib",
            "Edit_Bitmap_Dots",
            "Bitmap_Dots",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Blur"      ,0x29,KC_BITMAP,1,1,0x06000104,WERK_CLASS_COL_MOD,'b',
            //"beee",
            "bggg",
            "Edit_Bitmap_Blur",
            "Bitmap_Blur",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Mask"      ,0x2a,KC_BITMAP,3,3,0x06000301,WERK_CLASS_COL_ADD,0,
            "b",
            "Edit_Bitmap_Mask",
            "Bitmap_Mask",
            "Exec_Misc_Nop",
            { KC_BITMAP,KC_BITMAP,KC_BITMAP },
            { 0 },
          },
          {
            "HSCB"      ,0x2b,KC_BITMAP,1,1,0x06000104,WERK_CLASS_COL_MOD,'h',
            //"eeef",
            "gggg",
            "Edit_Bitmap_HSCB",
            "Bitmap_HSCB",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Rotate"    ,0x2c,KC_BITMAP,1,1,0x06000108,WERK_CLASS_COL_MOD,'r',
            "eggeebbb",
            "Edit_Bitmap_Rotate",
            "Bitmap_Rotate",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Distort"   ,0x2d,KC_BITMAP,2,2,0x06000202,WERK_CLASS_COL_ADD,'d',
            "eb",
            "Edit_Bitmap_Distort",
            "Bitmap_Distort",
            "Exec_Misc_Nop",
            { KC_BITMAP,KC_BITMAP },
            { 0 },
          },
          {
            "Normals"   ,0x2e,KC_BITMAP,1,1,0x06000102,WERK_CLASS_COL_MOD,'n',
            "eb",
            "Edit_Bitmap_Normals",
            "Bitmap_Normals",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Light"     ,0x2f,KC_BITMAP,1,1,0x0600010b,WERK_CLASS_COL_MOD,'L' | sKEYQ_SHIFT,
            "beeeeecceee",
            "Edit_Bitmap_Light",
            "Bitmap_Light",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Bump"      ,0x30,KC_BITMAP,2,2,0x0600020e,WERK_CLASS_COL_MOD,'B' | sKEYQ_SHIFT,
            "bgggeecceeecge",
            "Edit_Bitmap_Bump",
            "Bitmap_Bump",
            "Exec_Misc_Nop",
            { KC_BITMAP,KC_BITMAP },
            { 0 },
          },
          {
            "Text"      ,0x31,KC_BITMAP,1,1,0x468a0109,WERK_CLASS_COL_MOD,'t',
            "eeeecbbee",
            "Edit_Bitmap_Text",
            "Bitmap_Text",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Cell"      ,0x32,KC_BITMAP,0,0,0x0600000d,WERK_CLASS_COL_NEW,0,
            "bbcccbbeebebf",
            "Edit_Bitmap_Cell",
            "Bitmap_Cell",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Wavelet"   ,0x33,KC_BITMAP,1,1,0x06000102,WERK_CLASS_COL_MOD,0,
            "be",
            "Edit_Bitmap_Wavelet",
            "Bitmap_Wavelet",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Gradient"  ,0x34,KC_BITMAP,0,0,0x06000008,WERK_CLASS_COL_NEW,'G' | sKEYQ_SHIFT,
            "bbcceeeb",
            "Edit_Bitmap_Gradient",
            "Bitmap_Gradient",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Range"         ,0x35,KC_BITMAP,1,1,0x06000103,WERK_CLASS_COL_MOD,0,
            "bcc",
            "Edit_Bitmap_Range",
            "Bitmap_Range",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "RotateMul"     ,0x36,KC_BITMAP,1,1,0x0600010a,WERK_CLASS_COL_MOD,sKEYQ_SHIFT | 'R',
            "eggeebcbbc",
            "Edit_Bitmap_RotateMul",
            "Bitmap_RotateMul",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Twirl"         ,0x37,KC_BITMAP,1,1,0x06000107,WERK_CLASS_COL_MOD,0,
            "ggeeeeb",
            "Edit_Bitmap_Twirl",
            "Bitmap_Twirl",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Sharpen"       ,0x38,KC_BITMAP,1,1,0x06000104,WERK_CLASS_COL_MOD,0,
            "beee",
            "Edit_Bitmap_Sharpen",
            "Bitmap_Sharpen",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "GlowRect"      ,0x39,KC_BITMAP,1,1,0x0600010b,WERK_CLASS_COL_MOD,'g',
            "eeeeeeceebb",
            "Edit_Bitmap_GlowRect",
            "Bitmap_GlowRect",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Import"        ,0x3a,KC_BITMAP,0,0,0x46090000,WERK_CLASS_COL_NEW,0,
            "",
            "Edit_Bitmap_Import",
            "Bitmap_Import",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "ColorBalance"  ,0x3b,KC_BITMAP,1,1,0x06000109,WERK_CLASS_COL_MOD,'c',
            "eeeeeeeee",
            "Edit_Bitmap_ColorBalance",
            "Bitmap_ColorBalance",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Unwrap"        ,0x3c,KC_BITMAP,1,1,0x06000101,WERK_CLASS_COL_MOD,0,
            "b",
            "Edit_Bitmap_Unwrap",
            "Bitmap_Unwrap",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Bricks"        ,0x3d,KC_BITMAP,0,0,0x0600000e,WERK_CLASS_COL_NEW,0,
            "bbcccff" "bbbbbff",
            "Edit_Bitmap_Bricks",
            "Bitmap_Bricks",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Bulge"         ,0x3e,KC_BITMAP,1,1,0x06000101,WERK_CLASS_COL_MOD,0,
            "g",
            "Edit_Bitmap_Bulge",
            "Bitmap_Bulge",
            "Exec_Misc_Nop",
            { KC_BITMAP },
            { 0 },
          },
          {
            "Render"        ,0x3f,KC_BITMAP,1,1,0x46000102,WERK_CLASS_COL_NEW,0,
            "bb",
            "Edit_Bitmap_Render",
            "Bitmap_Render",
            "Exec_Bitmap_Render",
            { KC_IPP },
            { 0 },
          },
          {
            "RenderAuto"    ,0x40,KC_BITMAP,1,1,0x46000103,WERK_CLASS_COL_NEW,0,
            "bbb",
            "Edit_Bitmap_RenderAuto",
            "Bitmap_RenderAuto",
            "Exec_Bitmap_RenderAuto",
            { KC_MINMESH },
            { 0 },
          },

          /****************************************************************************/

            {
              "Dummy"         ,0x60,KC_EFFECT,0,0,0x00001003,WERK_CLASS_COL_NEW,0,
              "fff",
              "Edit_Effect_Dummy",
              "Init_Effect_Dummy",
              "Exec_Effect_Dummy",
              { 0 },
              { KC_MATERIAL },
            },
            {
              "Print"         ,0x61,KC_EFFECT,0,0,0x00011006,WERK_CLASS_COL_NEW,0,
              "ifffff",
              "Edit_Effect_Print",
              "Init_Effect_Print",
              "Exec_Effect_Print",
              { 0 },
              { KC_MATERIAL },
            },
            /*
                {
                "Particles"     ,0x62,KC_EFFECT,0,0,0x00001018,WERK_CLASS_COL_NEW,0,
                "bsffffffcccfffff" "ffffffff",
                "Edit_Effect_Particles,
                "Init_Effect_Particles,
                "Exec_Effect_Particles,
                { 0 },
                { KC_MATERIAL },
              },
            */
              {
                "PartEmitter"   ,0x63,KC_SCENE,0,0,0x00000011,WERK_CLASS_COL_NEW,0,
                "bbsff" "ffffffffffff",
                "Edit_Effect_PartEmitter",
                "Init_Effect_PartEmitter",
                "Exec_Effect_PartEmitter",
                { 0 },
                { 0 },
              },
              {
                "PartSystem"    ,0x64,KC_EFFECT,0,0,0x0000100c,WERK_CLASS_COL_NEW,0,
                "bscccffffffb",
                "Edit_Effect_PartSystem",
                "Init_Effect_PartSystem",
                "Exec_Effect_PartSystem",
                { 0 },
                { KC_MATERIAL },
              },
              {
                "Chaos1"         ,0x65,KC_EFFECT,0,0,0x0000100d,WERK_CLASS_COL_NEW,0,
                "fffffffffbbbi",
                "Edit_Effect_Chaos1",
                "Init_Effect_Chaos1",
                "Exec_Effect_Chaos1",
                { 0 },
                { KC_MATERIAL },
              },
              {
                "Tourque"        ,0x66,KC_EFFECT,0,0,0x0000200f,WERK_CLASS_COL_NEW,0,
                "biibffffffffffb",
                "Edit_Effect_Tourque",
                "Init_Effect_Tourque",
                "Exec_Effect_Tourque",
                { 0 },
                { KC_MATERIAL,KC_MESH },
              },
              {
                "Stream"        ,0x67,KC_EFFECT,0,0,0x00001024,WERK_CLASS_COL_NEW,0,
                "biibbfff"          // misc
                "ffffffffffffffff"  // pos
                "ffff"              // stuff
                "ffffffff",         // light
                "Edit_Effect_Stream",
                "Init_Effect_Stream",
                "Exec_Effect_Stream",
                { 0 },
                { KC_MATERIAL },
              },
              {
                "ImgLayer"      ,0x68,KC_EFFECT,0,1,0x40090104,WERK_CLASS_COL_NEW,0,
                "b-gb",
                "Edit_Effect_ImageLayer",
                "Init_Effect_ImageLayer",
                "Exec_Effect_ImageLayer",
                { KC_BITMAP },
                { 0 },
              },
              {
                "Billboards"       ,0x69,KC_EFFECT,2,2,0x00000204,WERK_CLASS_COL_NEW,0,
                "fffb",
                "Edit_Effect_Billboards",
                "Init_Effect_Billboards",
                "Exec_Effect_Billboards",
                { KC_MINMESH,KC_MATERIAL },
                { 0 },
              },
              {
                "WalkTheSpline"       ,0x6a,KC_SCENE,2,2,0x00000206,WERK_CLASS_COL_NEW,0,
                "ffibff",
                "Edit_Effect_WalkTheSpline",
                "Init_Effect_WalkTheSpline",
                "Exec_Effect_WalkTheSpline",
                { KC_MINMESH,KC_SPLINE },
                { 0 },
              },
              {
                "ChainLine",        0x6b,KC_EFFECT,0,0,0x00001015,WERK_CLASS_COL_NEW,0,
                "ffffffbbfffff"
                "fffbfffb",
                "Edit_Effect_ChainLine",
                "Init_Effect_ChainLine",
                "Exec_Effect_ChainLine",
                { 0 },
                { KC_MATERIAL },
              },
              {
                "aRTifakktory"       ,0x6c,KC_EFFECT,0,0,0x00000005,WERK_CLASS_COL_NEW,0,
                "bggbb",
                "Edit_Effect_JPEG",
                "Init_Effect_JPEG",
                "Exec_Effect_JPEG",
                { 0 },
                { 0 },
              },
              {
                "LineShuffle"        ,0x6d,KC_EFFECT,0,0,0x00000001,WERK_CLASS_COL_NEW,0,
                "b",
                "Edit_Effect_LineShuffle",
                "Init_Effect_LineShuffle",
                "Exec_Effect_LineShuffle",
                { 0 },
                { 0 },
              },
              {
                "BillboardField", 0x6e,KC_EFFECT,1,1,0x0000010f,WERK_CLASS_COL_NEW,0,
                "fffb" "fffffffibff",
                "Edit_Effect_BillboardField",
                "Init_Effect_BillboardField",
                "Exec_Effect_BillboardField",
                { KC_MATERIAL },
                { 0 },
              },
              {
                "BP06Spirit"    , 0x6f,KC_EFFECT,0,0,0x00002011,WERK_CLASS_COL_NEW,0,
                "fff" "fffffccciffffi" ,
                "Edit_Effect_BP06Spirit",
                "Init_Effect_BP06Spirit",
                "Exec_Effect_BP06Spirit",
                { 0 },
                { KC_MATERIAL,KC_MATERIAL },
              },
              {
                "BP06Jungle"   , 0x70,KC_EFFECT,0,0,0x0000100c,WERK_CLASS_COL_NEW,0,
                "bbffff" "ffffff",
                "Edit_Effect_BP06Jungle",
                "Init_Effect_BP06Jungle",
                "Exec_Effect_BP06Jungle",
                { 0 },
                { KC_MATERIAL },
              },


              /****************************************************************************/

                {
                  "Cube"          ,0x81,KC_MESH,0,0,0x0600000d,WERK_CLASS_COL_NEW,'q',
                  //"bbbbfffeeefff",
                  "bbbbggggggfff",
                  "Edit_Mesh_Cube",
                  "Mesh_Cube",
                  "Exec_Misc_Nop",
                  { 0 },
                  { 0 },
                },
                {
                  "Cylinder"      ,0x82,KC_MESH,0,0,0x06000005,WERK_CLASS_COL_NEW,'z',
                  "bbbbb",
                  "Edit_Mesh_Cylinder",
                  "Mesh_Cylinder",
                  "Exec_Misc_Nop",
                  { 0 },
                  { 0 },
                },
                {
                  "Torus"         ,0x83,KC_MESH,0,0,0x06000007,WERK_CLASS_COL_NEW,'o',
                  "bbffeeb",
                  "Edit_Mesh_Torus",
                  "Mesh_Torus",
                  "Exec_Misc_Nop",
                  { 0 },
                  { 0 },
                },
                {
                  "Sphere"        ,0x84,KC_MESH,0,0,0x06000002,WERK_CLASS_COL_NEW,'h',
                  "bb",
                  "Edit_Mesh_Sphere",
                  "Mesh_Sphere",
                  "Exec_Misc_Nop",
                  { 0 },
                  { 0 },
                },

                {
                  "Select All"    ,0x85,KC_MESH,1,1,0x06000102,WERK_CLASS_COL_MOD,0,
                  "mb",
                  "Edit_Mesh_SelectAll",
                  "Mesh_SelectAll",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Select Cube"   ,0x86,KC_MESH,1,1,0x06000108,WERK_CLASS_COL_MOD,0,
                  "mbffffff",
                  "Edit_Mesh_SelectCube",
                  "Mesh_SelectCube",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },

                {
                  "Subdivide"     ,0x87,KC_MESH,1,1,0x46000103,WERK_CLASS_COL_XTR,'u',
                  "bEb",
                  "Edit_Mesh_Subdivide",
                  "Mesh_Subdivide",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Transform"     ,0x88,KC_MESH,1,1,0x4600010a,WERK_CLASS_COL_MOD,'t',
                  "bGGGGGGGGG",
                  "Edit_Mesh_Transform",
                  "Mesh_Transform",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "TransEx"   ,0x89,KC_MESH,1,1,0x4600010c,WERK_CLASS_COL_MOD,'T' | sKEYQ_SHIFT,
                  "bGGGGGGFFFbb",
                  "Edit_Mesh_TransformEx",
                  "Mesh_TransformEx",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Crease"        ,0x8a,KC_MESH,1,1,0x06000103,WERK_CLASS_COL_MOD,0,
                  "bbb",
                  "Edit_Mesh_Crease",
                  "Mesh_Crease",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "UnCrease"      ,0x8b,KC_MESH,1,1,0x06000103,WERK_CLASS_COL_MOD,0,
                  "bbb",
                  "Edit_Mesh_UnCrease",
                  "Mesh_UnCrease",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Triangulate"   ,0x8c,KC_MESH,1,1,0x06000103,WERK_CLASS_COL_XTR,0,
                  "bbb",
                  "Edit_Mesh_Triangulate",
                  "Mesh_Triangulate",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Cut"           ,0x8d,KC_MESH,1,1,0x06000104,WERK_CLASS_COL_XTR,'x',
                  "eefb",
                  "Edit_Mesh_Cut",
                  "Mesh_Cut",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Extrude Normal",0x8e,KC_MESH,1,1,0x46000102,WERK_CLASS_COL_XTR,'E' | sKEYQ_SHIFT,
                  "bF",
                  "Edit_Mesh_ExtrudeNormal",
                  "Mesh_ExtrudeNormal",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Displace"      ,0x8f,KC_MESH,2,2,0x46000204,WERK_CLASS_COL_XTR,'d',
                  "bFFF",
                  "Edit_Mesh_Displace",
                  "Mesh_Displace",
                  "Exec_Misc_Nop",
                  { KC_MESH,KC_BITMAP },
                  { 0 },
                },
                {
                  "Bevel"         ,0x90,KC_MESH,1,1,0x46000104,WERK_CLASS_COL_XTR,0,
                  "bFFb",
                  "Edit_Mesh_Bevel",
                  "Mesh_Bevel",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Perlin"        ,0x91,KC_MESH,1,1,0x4600010d,WERK_CLASS_COL_XTR,'p',
                  "bFFFEEEFFFFFF",
                  "Edit_Mesh_Perlin",
                  "Mesh_Perlin",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Add"           ,0x92,KC_MESH,1,KK_MAXINPUT,0x07000000,WERK_CLASS_COL_ADD,'a',
                  "",
                  "Edit_Mesh_Add",
                  "Mesh_Add",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Delete Faces"  ,0x93,KC_MESH,1,1,0x06000101,WERK_CLASS_COL_MOD,'D' | sKEYQ_SHIFT,
                  "b",
                  "Edit_Mesh_DeleteFaces",
                  "Mesh_DeleteFaces",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Select Random" ,0x94,KC_MESH,1,1,0x06000104,WERK_CLASS_COL_MOD,'r',
                  "mbbb",
                  "Edit_Mesh_SelectRandom",
                  "Mesh_SelectRandom",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Multiply"      ,0x95,KC_MESH,1,1,0x46000111,WERK_CLASS_COL_ADD,'M' | sKEYQ_SHIFT,
                  //"FFFEEEFFFbbFFEEEF",
                  "GGGGGGFFFbbGGGGGGF",
                  "Edit_Mesh_Multiply",
                  "Mesh_Multiply",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },

                {
                  "BeginRec" ,0x99,KC_MESH,1,1,0x06000100,WERK_CLASS_COL_ADD,0,
                  "",
                  "Edit_Mesh_BeginRecord",
                  "Mesh_BeginRecord",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "Extrude"  ,0x9a,KC_MESH,1,1,0x4600010d,WERK_CLASS_COL_XTR,'e',
                  "bsbbFFFFFFEEE",
                  "Edit_Mesh_Extrude",
                  "Mesh_Extrude",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { 0 },
                },
                {
                  "CollCube" ,0x9c,KC_MESH,0,1,0x1600210e,WERK_CLASS_COL_NEW,'Q' | sKEYQ_SHIFT,
                  "FFFFFFbbbbbbbi",
                  //"GGGGGGbbbbbbbi",
                  "Edit_Mesh_CollisionCube",
                  "Mesh_CollisionCube",
                  "Exec_Misc_Nop",
                  { KC_MESH },
                  { KC_ANY,KC_SCENE },
                },
                {
                  "Grid"     ,0x9d,KC_MESH,0,0,0x06000003,WERK_CLASS_COL_NEW,'g',
                  "bbb",
                  "Edit_Mesh_Grid",
                  "Mesh_Grid",
                  "Exec_Misc_Nop",
                  { 0 },
                  { 0 },
                },
                /*{
                  "Lightmap"      ,0x9e,KC_MESH,1,1,0x06000104,WERK_CLASS_COL_XTR,0,
                  "",
                  "Edit_Mesh_Lightmap,
                  Mesh_Lightmap,
                  "Exec_Misc_Nop",
                  { KC_MESH },
                },
                {
                  "MapLight"      ,0x9f,KC_MESH,1,1,0x06000105,WERK_CLASS_COL_XTR,0,
                  "ffffc",
                  "Edit_Mesh_MapLight,
                  Mesh_MapLight,
                  "Exec_Misc_Nop",
                  { KC_MESH },
                },*/
                {
                  "Bend"     ,0xa0,KC_MESH,1,1,0x46000118,WERK_CLASS_COL_XTR,'b',
                  "b"
                  "GGGGGGFFF"
                  "GGGGGGFFF"
  /*"FFFEEEFFF"
  "FFFEEEFFF"*/
  "EEFF"
  "b",
  "Edit_Mesh_Bend",
  "Mesh_Bend",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "Select Logic" ,0xa1,KC_MESH,1,1,0x06000104,WERK_CLASS_COL_MOD,0,
  "mmmb",
  "Edit_Mesh_SelectLogic",
  "Mesh_SelectLogic",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "Select Grow" , 0xa2,KC_MESH,1,1,0x06000104,WERK_CLASS_COL_MOD,0,
  "ssbb",
  "Edit_Mesh_SelectGrow",
  "Mesh_SelectGrow",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "Invert" , 0xa3,KC_MESH,1,1,0x06000100,WERK_CLASS_COL_MOD,0,
  "",
  "Edit_Mesh_Invert",
  "Mesh_Invert",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "Set Pivot" ,0xa4,KC_MESH,1,1,0x06000104,WERK_CLASS_COL_MOD,0,
  "bfff",
  "Edit_Mesh_SetPivot",
  "Mesh_SetPivot",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "UVProject" ,0xa5,KC_MESH,1,1,0x0600010b,WERK_CLASS_COL_MOD,0,
  "bfffffffffb",
  //"beeeeeefffb",
  "Edit_Mesh_UVProjection",
  "Mesh_UVProjection",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "Center"    ,0xa6,KC_MESH,1,1,0x06000102,WERK_CLASS_COL_MOD,'c',
  "bb",
  "Edit_Mesh_Center",
  "Mesh_Center",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "AutoColl"  ,0xa7,KC_MESH,1,1,0x06000106,WERK_CLASS_COL_MOD,'A' | sKEYQ_SHIFT,
  "fbbbb",
  "Edit_Mesh_AutoCollision",
  "Mesh_AutoCollision",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "SelectSphere"  ,0xa8,KC_MESH,1,1,0x06000108,WERK_CLASS_COL_MOD,0,
  "mbffffff",
  "Edit_Mesh_SelectSphere",
  "Mesh_SelectSphere",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "SelectFace"    ,0xa9,KC_MESH,1,1,0x06000103,WERK_CLASS_COL_MOD,0,
  "bbi",
  "Edit_Mesh_SelectFace",
  "Mesh_SelectFace",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "SelectAngle"   ,0xaa,KC_MESH,1,1,0x06000105,WERK_CLASS_COL_MOD,0,
  "bbeee",
  "Edit_Mesh_SelectAngle",
  "Mesh_SelectAngle",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "Bend 2"        ,0xab,KC_MESH,1,1,0x06000108,WERK_CLASS_COL_XTR,'B' | sKEYQ_SHIFT,
  "fffeeeff",
  "Edit_Mesh_Bend2",
  "Mesh_Bend2",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "SmAngle"       ,0xac,KC_MESH,1,1,0x06000101,WERK_CLASS_COL_MOD,0,
  "f",
  "Edit_Mesh_SmoothAngle",
  "Mesh_SmoothAngle",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "Color"         ,0xad,KC_MESH,1,1,0x06000109,WERK_CLASS_COL_MOD,0,
  "fffeecffb",
  "Edit_Mesh_Color",
  "Mesh_Color",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "Bend Spline"   ,0xae,KC_MESH,1,1,0x06100107,WERK_CLASS_COL_XTR,0,
  "fffeeef",
  "Edit_Mesh_BendS",
  "Mesh_BendS",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "Light Slot"    ,0xaf,KC_MESH,0,1,0x06000006,WERK_CLASS_COL_MOD,0,
  "fffcff",
  "Edit_Mesh_LightSlot",
  "Mesh_LightSlot",
  "Exec_Misc_Nop",
  { 0 },
  { 0 },
},
{
  "ShadowEnable"  ,0xb0,KC_MESH,1,1,0x06000101,WERK_CLASS_COL_MOD,0,
  "b",
  "Edit_Mesh_ShadowEnable",
  "Mesh_ShadowEnable",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "XSI"           ,0xb1,KC_MESH,0,1,0x06010000,WERK_CLASS_COL_NEW,'X' | sKEYQ_SHIFT,
  "",
  "Edit_Mesh_XSI",
  "Mesh_XSI",
  "Exec_Misc_Nop",
  { 0 },
  { 0 },
},
{
  "BSP"           ,0xb2,KC_SMESH,1,1,0x06000100,WERK_CLASS_COL_MOD,0,
  "",
  "Edit_Misc_Nop",
  "Mesh_BSP",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "SingleVert"    ,0xb3,KC_MESH,0,1,0x06000000,WERK_CLASS_COL_NEW,'V' | sKEYQ_SHIFT,
  "",
  "Edit_Mesh_SingleVert",
  "Mesh_SingleVert",
  "Exec_Misc_Nop",
  { 0 },
  { 0 },
},
{
  "Multiply 2"    ,0xb4,KC_MESH,1,KK_MAXINPUT,0x07000014,WERK_CLASS_COL_ADD,0,
  "bbbbgggbbbgggbbbbggg",
  "Edit_Mesh_Multiply2",
  "Mesh_Multiply2",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},
{
  "<- Mesh"    ,0xb5,KC_MINMESH,1,1,0x06000100,WERK_CLASS_COL_MOD,0,
  "",
  "Edit_Mesh_ToMin",
  "Mesh_ToMin",
  "Exec_Misc_Nop",
  { KC_MESH },
  { 0 },
},

/****************************************************************************/
/****************************************************************************/

  {
    "SingleVert"    ,0x100,KC_MINMESH,0,1,0x06000000,WERK_CLASS_COL_NEW,'V' | sKEYQ_SHIFT,
    "",
    "Edit_MinMesh_SingleVert",
    "MinMesh_SingleVert",
    "Exec_Misc_Nop",
    { 0 },
    { 0 },
  },
  {
    "Grid"          ,0x101,KC_MINMESH,0,0,0x06000003,WERK_CLASS_COL_NEW,'g',
    "bbb",
    "Edit_MinMesh_Grid",
    "MinMesh_Grid",
    "Exec_Misc_Nop",
    { 0 },
    { 0 },
  },
  {
    "Cube"          ,0x102,KC_MINMESH,0,0,0x0600000d,WERK_CLASS_COL_NEW,'q',
    "bbbbggggggfff",
    "Edit_MinMesh_Cube",
    "MinMesh_Cube",
    "Exec_Misc_Nop",
    { 0 },
    { 0 },
  },
  {
    "Torus"         ,0x103,KC_MINMESH,0,0,0x06000007,WERK_CLASS_COL_NEW,'o',
    "bbffeeb",
    "Edit_MinMesh_Torus",
    "MinMesh_Torus",
    "Exec_Misc_Nop",
    { 0 },
    { 0 },
  },
  {
    "Sphere"        ,0x104,KC_MINMESH,0,0,0x06000002,WERK_CLASS_COL_NEW,'h',
    "bb",
    "Edit_MinMesh_Sphere",
    "MinMesh_Sphere",
    "Exec_Misc_Nop",
    { 0 },
    { 0 },
  },
  {
    "Cylinder"      ,0x105,KC_MINMESH,0,0,0x06000005,WERK_CLASS_COL_NEW,'z',
    "bbbbb",
    "Edit_MinMesh_Cylinder",
    "MinMesh_Cylinder",
    "Exec_Misc_Nop",
    { 0 },
    { 0 },
  },
  {
    "XSI"           ,0x106,KC_MINMESH,0,1,0x06010000,WERK_CLASS_COL_NEW,'X' | sKEYQ_SHIFT,
    "",
    "Edit_MinMesh_XSI",
    "MinMesh_XSI",
    "Exec_Misc_Nop",
    { 0 },
    { 0 },
  },
  {
    "MTetra"        ,0x107,KC_MINMESH,0,1,0x06010001,WERK_CLASS_COL_NEW,0,
    "g",
    "Edit_MinMesh_MTetra",
    "MinMesh_MTetra",
    "Exec_Misc_Nop",
    { 0 },
    { 0 },
  },
  {
    "Kopuli"        ,0x10f,KC_MINMESH,0,1,0x06000000,WERK_CLASS_COL_NEW,0,
    "",
    "Edit_MinMesh_Kopuli",
    "MinMesh_Kopuli",
    "Exec_Misc_Nop",
    { 0 },
    { 0 },
  },

  /****************************************************************************/

    {
      "MatLink"       ,0x110,KC_MINMESH,1,1,0x06001102,WERK_CLASS_COL_MOD,'m',
      "bb",
      "Edit_MinMesh_MatLink",
      "MinMesh_MatLink",
      "Exec_Misc_Nop",
      { KC_MINMESH },
      { KC_MATERIAL },
    },
    {
      "Add"           ,0x111,KC_MINMESH,1,KK_MAXINPUT,0x07000000,WERK_CLASS_COL_ADD,'a',
      "",
      "Edit_MinMesh_Add",
      "MinMesh_Add",
      "Exec_Misc_Nop",
      { KC_MINMESH },
      { 0 },
    },
    {
      "Select All"     ,0x112,KC_MINMESH,1,1,0x06000101,WERK_CLASS_COL_MOD,0,
      "b",
      "Edit_MinMesh_SelectAll",
      "MinMesh_SelectAll",
      "Exec_Misc_Nop",
      { KC_MINMESH },
      { KC_MATERIAL },
    },
    {
      "Select Cube"    ,0x113,KC_MINMESH,1,1,0x06000107,WERK_CLASS_COL_MOD,0,
      "bffffff",
      "Edit_MinMesh_SelectCube",
      "MinMesh_SelectCube",
      "Exec_Misc_Nop",
      { KC_MINMESH },
      { 0 },
    },
    {
      "Delete Faces"   ,0x114,KC_MINMESH,1,1,0x06000100,WERK_CLASS_COL_MOD,0,
      "",
      "Edit_MinMesh_DeleteFaces",
      "MinMesh_DeleteFaces",
      "Exec_Misc_Nop",
      { KC_MINMESH },
      { KC_MATERIAL },
    },
    {
      "Invert"         ,0x115,KC_MINMESH,1,1,0x06000100,WERK_CLASS_COL_MOD,0,
      "b",
      "Edit_MinMesh_Invert",
      "MinMesh_Invert",
      "Exec_Misc_Nop",
      { KC_MINMESH },
      { KC_MATERIAL },
    },
    {
      "MatLinkId"      ,0x116,KC_MINMESH,1,1,0x06001102,WERK_CLASS_COL_MOD,0,
      "bb",
      "Edit_MinMesh_MatLinkId",
      "MinMesh_MatLinkId",
      "Exec_Misc_Nop",
      { KC_MINMESH },
      { KC_MATERIAL },
    },
    {
      "MatInput"       ,0x117,KC_MINMESH,2,2,0x06000202,WERK_CLASS_COL_MOD,'M' | sKEYQ_SHIFT,
      "bb",
      "Edit_MinMesh_MatInput",
      "MinMesh_MatLink",
      "Exec_Misc_Nop",
      { KC_MINMESH,KC_MATERIAL },
      { 0 },
    },

    /****************************************************************************/

      {
        "Transform"     ,0x120,KC_MINMESH,1,1,0x0600010a,WERK_CLASS_COL_MOD,'t',
        "bGGGGGGGGG",
        "Edit_MinMesh_Transform",
        "MinMesh_TransformEx",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "TransEx"       ,0x121,KC_MINMESH,1,1,0x0600010c,WERK_CLASS_COL_MOD,'T' | sKEYQ_SHIFT,
        "bGGGGGGFFFbb",
        "Edit_MinMesh_TransformEx",
        "MinMesh_TransformEx",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },

      {
        "Extrude Normal",0x122,KC_MINMESH,1,1,0x06000102,WERK_CLASS_COL_XTR,'E' | sKEYQ_SHIFT,
        "bF",
        "Edit_MinMesh_ExtrudeNormal",
        "MinMesh_ExtrudeNormal",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "Displace"      ,0x123,KC_MINMESH,2,2,0x06000204,WERK_CLASS_COL_XTR,'d',
        "bFFF",
        "Edit_MinMesh_Displace",
        "MinMesh_Displace",
        "Exec_Misc_Nop",
        { KC_MINMESH,KC_BITMAP },
        { 0 },
      },
      {
        "Perlin"        ,0x124,KC_MINMESH,1,1,0x0600010d,WERK_CLASS_COL_XTR,'p',
        "bFFFEEEFFFFFF",
        "Edit_MinMesh_Perlin",
        "MinMesh_Perlin",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "Bend 2"        ,0x125,KC_MINMESH,1,1,0x06000108,WERK_CLASS_COL_XTR,'B' | sKEYQ_SHIFT,
        "fffeeeff",
        "Edit_MinMesh_Bend2",
        "MinMesh_Bend2",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "Extrude"        ,0x126,KC_MINMESH,1,1,0x0600105,WERK_CLASS_COL_XTR,'e',
        "bbggg",
        "Edit_MinMesh_Extrude",
        "MinMesh_Extrude",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "BakeAnimation"  ,0x127,KC_MINMESH,1,1,0x06000102,WERK_CLASS_COL_XTR,0,
        "FF",
        "Edit_MinMesh_BakeAnimation",
        "MinMesh_BakeAnimation",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "BoneChain"  ,0x128,KC_MINMESH,1,1,0x06000108,WERK_CLASS_COL_XTR,0,
        "ffffffib",
        "Edit_MinMesh_BoneChain",
        "MinMesh_BoneChain",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "BoneTrain"  ,0x129,KC_MINMESH,2,3,0x06000202,WERK_CLASS_COL_XTR,0,
        "fb",
        "Edit_MinMesh_BoneTrain",
        "MinMesh_BoneTrain",
        "Exec_Misc_Nop",
        { KC_MINMESH,KC_SPLINE,KC_SPLINE },
        { 0 },
      },
      {
        "Triangulate",0x12a,KC_MINMESH,1,1,0x06000100,WERK_CLASS_COL_MOD,0,
        "",
        "Edit_MinMesh_Triangulate",
        "MinMesh_Triangulate",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      /*{
        "Compress"  ,0x12b,KC_MINMESH,1,1,0x06000100,WERK_CLASS_COL_MOD,0,
        "",
        "Edit_MinMesh_Compress,
        MinMesh_Compress,
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },*/
      {
        "Pipe",0x12c,KC_MINMESH,2,4,0x06000403,WERK_CLASS_COL_MOD,0,
        "bff",
        "Edit_MinMesh_Pipe",
        "MinMesh_Pipe",
        "Exec_Misc_Nop",
        { KC_SPLINE,KC_MINMESH,KC_MINMESH,KC_MINMESH },
        { 0 },
      },
      {
        "ScaleAnim"       ,0x12d,KC_MINMESH,1,1,0x06000101,WERK_CLASS_COL_MOD,0,
        "f",
        "Edit_MinMesh_ScaleAnim",
        "MinMesh_ScaleAnim",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "RenderAutoMap"     ,0x12e,KC_MINMESH,1,1,0x06000101,WERK_CLASS_COL_MOD,0,
        "b",
        "Edit_MinMesh_RenderAutoMap",
        "MinMesh_RenderAutoMap",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "Multiply"          ,0x12f,KC_MINMESH,1,1,0x46000111,WERK_CLASS_COL_ADD,0,
        "GGGGGGFFFbbGGGGGGF",
        "Edit_MinMesh_Multiply",
        "MinMesh_Multiply",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "Multiply 2"        ,0x130,KC_MINMESH,1,KK_MAXINPUT,0x07000014,WERK_CLASS_COL_ADD,0,
        "bbbbgggbbbgggbbbbggg",
        "Edit_MinMesh_Multiply2",
        "MinMesh_Multiply2",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "Center"            ,0x131,KC_MINMESH,1,1,0x06000101,WERK_CLASS_COL_MOD,0,
        "b",
        "Edit_MinMesh_Center",
        "MinMesh_Center",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },
      {
        "Select Logic"      ,0x132,KC_MINMESH,1,1,0x06000101,WERK_CLASS_COL_MOD,0,
        "b",
        "Edit_MinMesh_SelectLogic",
        "MinMesh_SelectLogic",
        "Exec_Misc_Nop",
        { KC_MINMESH },
        { 0 },
      },

      /****************************************************************************/
      /****************************************************************************/

        {
          "Scene"         ,0xc0,KC_SCENE,0,1,0x0000010a,WERK_CLASS_COL_NEW,'n',
          //"fffeeefffb",
          "ggggggfffb",
          "Edit_Scene_Scene",
          "Init_Scene_Scene",
          "Exec_Scene_Scene",
          { KC_ANY },
          { 0 },
        },
        {
          "Add"           ,0xc1,KC_SCENE,1,15,0x05000000,WERK_CLASS_COL_ADD,'a',
          "",
          "Edit_Scene_Add",
          "Init_Scene_Add",
          "Exec_Scene_Add",
          { KC_ANY },
          { 0 },
        },
        {
          "Multiply"      ,0xc2,KC_SCENE,1,1,0x0000010a,WERK_CLASS_COL_MOD,'m',
          //"fffeeefffb",
          "ggggggfffb",
          "Edit_Scene_Multiply",
          "Init_Scene_Multiply",
          "Exec_Scene_Multiply",
          { KC_ANY },
          { 0 },
        },
        {
          "Transform"     ,0xc3,KC_SCENE,1,1,0x00000109,WERK_CLASS_COL_MOD,'t',
          //"fffeeefff",
          "ggggggfff",
          "Edit_Scene_Transform",
          "Init_Scene_Transform",
          "Exec_Scene_Transform",
          { KC_ANY },
          { 0 },
        },
        {
          "Light"         ,0xc4,KC_SCENE,0,0,0x0000000b,WERK_CLASS_COL_MOD,'L' | sKEYQ_SHIFT,
          "eeefffbecff",
          "Edit_Scene_Light",
          "Init_Scene_Light",
          "Exec_Scene_Light",
          { 0 },
          { 0 },
        },
        /*{
            "MapLight"      ,0xc5,KC_SCENE,1,1,0x0000010b,WERK_CLASS_COL_MOD,'M'|sKEYQ_SHIFT,
            "ffffffffffc",
            "Edit_Scene_MapLight,
            "Init_Scene_MapLight,
            "Exec_Scene_MapLight,
            { KC_SCENE },
            { 0 },
          },*/
          {
            "Particles"      ,0xc5,KC_SCENE,1,1,0x00100110,WERK_CLASS_COL_MOD,0,   // c5 was MapLight!
            //"fffeeefffb",
            "bibgggggggggf"
            "ggg",
            "Edit_Scene_Particles",
            "Init_Scene_Particles",
            "Exec_Scene_Particles",
            { KC_ANY },
            { 0 },
          },
          {
            "Camera"         ,0xc6,KC_SCENE,0,0,0x00000009,WERK_CLASS_COL_NEW,0,
            "fffeeefff",
            "Edit_Scene_Camera",
            "Init_Scene_Camera",
            "Exec_Scene_Camera",
            { 0 },
            { 0 },
          },
          {
            "Limb"          ,0xc7,KC_SCENE,2,2,0x00000209,WERK_CLASS_COL_XTR,0,
            "ffffffffb",
            "Edit_Scene_Limb",
            "Init_Scene_Limb",
            "Exec_Scene_Limb",
            { KC_ANY,KC_ANY },
            { 0 },
          },
          {
            "Walk"          ,0xc8,KC_SCENE,1,1,0x00100127,WERK_CLASS_COL_XTR,0,
            "bbfffbbffffff"
            "ffffffff" "ffffffff" "ffffffff"
            "ff",
            "Edit_Scene_Walk",
            "Init_Scene_Walk",
            "Exec_Scene_Walk",
            { KC_SCENE,KC_SCENE },
            { 0 },
          },
          {
            "Rotate"        ,0xc9,KC_SCENE,1,1,0x00000104,WERK_CLASS_COL_XTR,0,
            "fffb",
            "Edit_Scene_Rotate",
            "Init_Scene_Rotate",
            "Exec_Scene_Rotate",
            { KC_SCENE },
            { 0 },
          },
          {
            "Forward"       ,0xca,KC_SCENE,1,1,0x00000101,WERK_CLASS_COL_XTR,0,
            "f",
            "Edit_Scene_Forward",
            "Init_Scene_Forward",
            "Exec_Scene_Forward",
            { KC_SCENE },
            { 0 },
          },
          {
            "Sector"        ,0xcb,KC_SCENE,1,1,0x00000100,WERK_CLASS_COL_MOD,0,
            "",
            "Edit_Scene_Sector",
            "Init_Scene_Sector",
            "Exec_Scene_Sector",
            { KC_SCENE },
            { 0 },
          },
          {
            "Portal"        ,0xcd,KC_SCENE,0,1,0x00003108,WERK_CLASS_COL_ADD,0,
            "ffffffbe",
            "Edit_Scene_Portal",
            "Init_Scene_Portal",
            "Exec_Scene_Portal",
            { KC_SCENE },
            { KC_SCENE,KC_SCENE,KC_SCENE },
          },
          {
            "Physic"        ,0xce,KC_SCENE,0,1,0x0000010c,WERK_CLASS_COL_XTR,0,
            "bffffff" "ffffb",
            "Edit_Scene_Physic",
            "Init_Scene_Physic",
            "Exec_Scene_Physic",
            { KC_SCENE },
            { 0 },
          },
          {
            "ForceLights"   ,0xcf,KC_SCENE,1,1,0x00000102,WERK_CLASS_COL_XTR,0,
            "bb",
            "Edit_Scene_ForceLights",
            "Init_Scene_ForceLights",
            "Exec_Scene_ForceLights",
            { KC_SCENE },
            { 0 },
          },
          {
            "Adjust Pass"     ,0x180,KC_SCENE,1,1,0x00000101,WERK_CLASS_COL_MOD,0,
            "b",
            "Edit_Scene_AdjustPass",
            "Init_Scene_AdjustPass",
            "Exec_Scene_AdjustPass",
            { KC_ANY },
            { 0 },
          },
          {
            "Apply Spline"    ,0x181,KC_SCENE,2,2,0x00000201,WERK_CLASS_COL_MOD,0,
            "f",
            "Edit_Scene_ApplySpline",
            "Init_Scene_ApplySpline",
            "Exec_Scene_ApplySpline",
            { KC_SCENE,KC_SPLINE },
            { 0 },
          },
          {
            "Marker"          ,0x182,KC_SCENE,0,1,0x00000101,WERK_CLASS_COL_NEW,0,
            "b",
            "Edit_Scene_Marker",
            "Init_Scene_Marker",
            "Exec_Scene_Marker",
            { KC_SCENE },
            { 0 },
          },
          {
            "LOD"             ,0x183,KC_SCENE,1,2,0x00000201,WERK_CLASS_COL_ADD,0,
            "f",
            "Edit_Scene_LOD",
            "Init_Scene_LOD",
            "Exec_Scene_LOD",
            { KC_ANY,KC_ANY },
            { 0 },
          },
          {
            "Ambient"         ,0x184,KC_SCENE,0,0,0x00000001,WERK_CLASS_COL_MOD,'A' | sKEYQ_SHIFT,
            "c",
            "Edit_Scene_Ambient",
            "Init_Scene_Ambient",
            "Exec_Scene_Ambient",
            { 0 },
            { 0 },
          },

          /****************************************************************************/

          {
            "MatLink",0x96,KC_MESH,1,1,0x06001102,WERK_CLASS_COL_MOD,'m',
            "bb",
            "Edit_Mesh_MatLink",
            "Mesh_MatLink",
            "Exec_Misc_Nop",
            { KC_MESH },
            { KC_MATERIAL },
          },
          {
            "MatHack",0xd2,KC_SCENE,0,0,0x00001000,WERK_CLASS_COL_XTR,0,
            "",
            "Edit_Scene_MatHack",
            "Init_Scene_MatHack",
            "Exec_Scene_MatHack",
            { 0 },
            { KC_MATERIAL },
          },
          {
            "Material"     ,0xd0,KC_MATERIAL,0,1,0x26007140,WERK_CLASS_COL_MOD,'M' | sKEYQ_SHIFT,
            "iii-" // base special light pad
            "iiii" // tflags
            "iiiiiiiiiiiii--i" // combiners
            "ffffccccf-" // uvscale, colors, specpower, pad
            "fffeeefff" // uvxform1
            "ffeff" // uvxform2
            "iiifii--" // multimisc
            "iiiiffff", // multitflags/tscale
            "Edit_Material_Material",
            "Init_Material_Material",
            "Exec_Material_Material",
            { KC_MATERIAL },
            { KC_BITMAP,KC_BITMAP,KC_BITMAP,KC_BITMAP,
              KC_BITMAP,KC_BITMAP,KC_BITMAP, },
          },
          {
            "Add Material" ,0xd1,KC_MATERIAL,1,KK_MAXINPUT,0x07000000,WERK_CLASS_COL_MOD,'a',
            "",
            "Edit_Material_Add",
            "Material_Add",
            "Exec_Misc_Nop",
            { KC_MATERIAL },
          },
          {
            "Material 2.0" ,0xd3,KC_MATERIAL,0,3,0x20007326,WERK_CLASS_COL_MOD,'m',
            "iccgg---"    // general section
            "iiiigggg"    // texture section
            "iii-ggg-"    // bump/lighting section
            "ggggggggg"   // uvxform 1
            "ggggg",      // uvxform2
            "Edit_Material_Material20",
            "Init_Material_Material20",
            "Exec_Misc_Nop",
            { KC_BITMAP,KC_BITMAP,KC_BITMAP },
            { KC_BITMAP,KC_BITMAP,KC_BITMAP,KC_BITMAP,
              KC_BITMAP,KC_BITMAP,KC_BITMAP},
          },

  /****************************************************************************/

  {
    "Viewport"      ,0xf0,KC_IPP,1,2,0x08000218,WERK_CLASS_COL_NEW,'v',
    "bicggggggffffffcffggffff",
    "Edit_IPP_Viewport",
    "Init_IPP_Viewport",
    "Exec_IPP_Viewport",
    { KC_SCENE,KC_SPLINE },
    { 0 },
  },
  {
    "Blur"          ,0xe3,KC_IPP,1,1,0x08000105,WERK_CLASS_COL_MOD,'b',
    "bfebb",
    "Edit_IPP_Blur",
    "Init_IPP_Blur",
    "Exec_IPP_Blur",
    { KC_IPP },
    { 0 },
  },
  {
    "Copy"          ,0xe2,KC_IPP,1,1,0x08000103,WERK_CLASS_COL_MOD,'C' | sKEYQ_SHIFT,
    "bcf",
    "Edit_IPP_Copy",
    "Init_IPP_Copy",
    "Exec_IPP_Copy",
    { KC_IPP },
    { 0 },
  },
  {
    "Crashzoom"     ,0xe4,KC_IPP,1,1,0x08000106,WERK_CLASS_COL_MOD,'z',
    "bbgeee",
    "Edit_IPP_Crashzoom",
    "Init_IPP_Crashzoom",
    "Exec_IPP_Crashzoom",
    { KC_IPP },
    { 0 },
  },
  {
    "Sharpen"       ,0xe5,KC_IPP,1,1,0x08000104,WERK_CLASS_COL_MOD,0,
    "becb",
    "Edit_IPP_Sharpen",
    "Init_IPP_Sharpen",
    "Exec_IPP_Sharpen",
    { KC_IPP },
    { 0 },
  },
  {
    "Color"         ,0xe6,KC_IPP,1,1,0x08000104,WERK_CLASS_COL_ADD,'c',
    "bcbc",
    "Edit_IPP_Color",
    "Init_IPP_Color",
    "Exec_IPP_Color",
    { KC_IPP },
    { 0 },
  },
  {
    "Merge"         ,0xe7,KC_IPP,2,2,0x08000204,WERK_CLASS_COL_ADD,'m',
    "bbbc",
    "Edit_IPP_Merge",
    "Init_IPP_Merge",
    "Exec_IPP_Merge",
    { KC_IPP,KC_IPP },
    { 0 },
  },
  {
    "Mask"          ,0xe8,KC_IPP,3,3,0x08000301,WERK_CLASS_COL_XTR,'M' | sKEYQ_SHIFT,
    "b",
    "Edit_IPP_Mask",
    "Init_IPP_Mask",
    "Exec_IPP_Mask",
    { KC_IPP,KC_IPP,KC_IPP },
    { 0 },
  },
  {
    "Layer2D"       ,0xe9,KC_IPP,0,1,0x0800110b,WERK_CLASS_COL_MOD,'L' | sKEYQ_SHIFT,
    "bfffffffffb",
    "Edit_IPP_Layer2D",
    "Init_IPP_Layer2D",
    "Exec_IPP_Layer2D",
    { KC_IPP },
    { KC_MATERIAL },
  },
  {
    "Select"        ,0xea,KC_IPP,1,KK_MAXINPUT,0x01000000,WERK_CLASS_COL_ADD,0,
    "",
    "Edit_IPP_Select",
    "Init_IPP_Select",
    "Exec_IPP_Select",
    { KC_IPP },
    { 0 },
  },
  {
    "Rendertarget"  ,0xeb,KC_IPP,1,1,0x00001100,WERK_CLASS_COL_MOD,0,
    "",
    "Edit_IPP_RenderTarget",
    "Init_IPP_RenderTarget",
    "Exec_IPP_RenderTarget",
    { KC_IPP },
    { KC_BITMAP },
  },
  {
    "HSCB"          ,0xec,KC_IPP,1,1,0x08000105,WERK_CLASS_COL_ADD,0,
    "bgggg",
    "Edit_IPP_HSCB",
    "Init_IPP_HSCB",
    "Exec_IPP_HSCB",
    { KC_IPP },
    { 0 },
  },
  {
    "JPEG"          ,0xed,KC_IPP,1,1,0x08000103,WERK_CLASS_COL_ADD,0,
    "bbg",
    "Edit_IPP_JPEG",
    "Init_IPP_JPEG",
    "Exec_IPP_JPEG",
    { KC_IPP },
    { 0 },
  },

  /****************************************************************************/

    {
      0
    }
};

WerkClass2* FindWerkClass2(sInt id)
{
  sInt i;

  for (i = 0; WerkClasses2[i].Name; i++)
  {
    if (WerkClasses2[i].Id == id)
      return &WerkClasses2[i];
  }
  return 0;
}
