// this file is automatically generated from 'effect_colorcorrect.vsh', do not edit!

static sU32 g_effect_colorcorrect_vsh[] = {
  0xfffe0200,0x0200001f,0x80000000,0x900f0000,0x0200001f,0x80000005,0x900f0001,
  0x03000014,0xc00f0000,0x90e40000,0xa0e40000,0x02000001,0xe0030000,0x90e40001,
  0x0000ffff,
};