// this file is automatically generated from 'material20_vcolor.psh', do not edit!

static sU32 g_material20_vcolor_psh[] = {
  0xffff0200,0x0200001f,0x80000000,0x900f0000,0x02000001,0x800f0800,0x90e40000,
  0x0000ffff,
};