// this file is automatically generated from 'material20_vcolor.vsh', do not edit!

static sU32 g_material20_vcolor_vsh[] = {
  0xfffe0200,0x0200001f,0x80000000,0x900f0000,0x03000014,0xc00f0000,0x90e40000,
  0xa0e40000,0x02000001,0xd00f0000,0xa0e40004,0x0000ffff,
};