name: build_werkkzeug3

on:
  push:
    branches: [ "master", "trace" ]
  pull_request:
    branches: [ "master", "trace" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Build Werkkzeug
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;";
          msbuild 'werkkzeug3_kkrieger/wz3projects.sln' /p:configuration=Debug /p:platform=x86

      - name: Build GenThree
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;";
          msbuild 'genthree/genthree.sln' /p:configuration=Debug /p:platform=Win32

      # - run: Get-ChildItem -Recurse
        
      #- name: Get Current Date
      #  id: date
      #  run: echo "CURRENT_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      #- name: Echo Current Date To Log
      #  run: echo ${{ env.CURRENT_DATE }}

      - name: Upload to GitHub Actions Artifact Storage
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Kkrieger-Werkkzeug-#${{ github.run_number }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/werkkzeug3_kkrieger/example_cube/Debug/example_cube.exe
            ${{ github.workspace }}/werkkzeug3_kkrieger/player_demo/Debug/player_demo.exe
            ${{ github.workspace }}/werkkzeug3_kkrieger/player_intro/Debug/player_intro.exe
            ${{ github.workspace }}/werkkzeug3_kkrieger/player_kkrieger/Debug/player_kkrieger.exe
            ${{ github.workspace }}/werkkzeug3_kkrieger/shadercompile/Debug/shadercompile.exe
            ${{ github.workspace }}/werkkzeug3_kkrieger/werkkzeug3/Debug/werkkzeug3.exe
            ${{ github.workspace }}/werkkzeug3_kkrieger/data/*
            ${{ github.workspace }}/genthree/Debug/genthree.exe
            ${{ github.workspace }}/genthree/data/*
            ${{ github.workspace }}/docs/*
          if-no-files-found: warn
